package dev.foliaondemand.shim;

/**
 * AUTO-GENERATED by `cli mine-folia` from folia-26.1.2.jar.
 * One shim method per region-locked entity mutator, rerouting the call to the
 * entity's region thread. Do not edit — regenerate with `npm run cli -- mine-folia`.
 */
public final class ShimGenerated {
    public static void activate(org.bukkit.entity.Creaking e, org.bukkit.entity.Player a0) { Shim.onEntity(e, () -> e.activate(a0)); }
    public static boolean addBarterMaterial(org.bukkit.entity.Piglin e, org.bukkit.Material a0) { if (Shim.ownsEntity(e)) return e.addBarterMaterial(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.addBarterMaterial(a0)); return true; }
    public static boolean addCustomEffect(org.bukkit.entity.AreaEffectCloud e, org.bukkit.potion.PotionEffect a0, boolean a1) { if (Shim.ownsEntity(e)) return e.addCustomEffect(a0, a1); ShimCore.ownScheduler().runAtEntity(e, t -> e.addCustomEffect(a0, a1)); return true; }
    public static boolean addEffectToNextStew(org.bukkit.entity.MushroomCow e, io.papermc.paper.potion.SuspiciousEffectEntry a0, boolean a1) { if (Shim.ownsEntity(e)) return e.addEffectToNextStew(a0, a1); ShimCore.ownScheduler().runAtEntity(e, t -> e.addEffectToNextStew(a0, a1)); return true; }
    public static void addEquipmentLock(org.bukkit.entity.ArmorStand e, org.bukkit.inventory.EquipmentSlot a0, org.bukkit.entity.ArmorStand.LockType a1) { Shim.onEntity(e, () -> e.addEquipmentLock(a0, a1)); }
    public static void addExploredLocation(org.bukkit.entity.Sniffer e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.addExploredLocation(a0)); }
    public static boolean addMaterialOfInterest(org.bukkit.entity.Piglin e, org.bukkit.Material a0) { if (Shim.ownsEntity(e)) return e.addMaterialOfInterest(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.addMaterialOfInterest(a0)); return true; }
    public static boolean addPassenger(org.bukkit.entity.Entity e, org.bukkit.entity.Entity a0) { if (Shim.ownsEntity(e)) return e.addPassenger(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.addPassenger(a0)); return true; }
    public static boolean addScoreboardTag(org.bukkit.entity.Entity e, java.lang.String a0) { if (Shim.ownsEntity(e)) return e.addScoreboardTag(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.addScoreboardTag(a0)); return true; }
    public static boolean addTrades(org.bukkit.entity.Villager e, int a0) { if (Shim.ownsEntity(e)) return e.addTrades(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.addTrades(a0)); return true; }
    public static void attack(org.bukkit.entity.LivingEntity e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.attack(a0)); }
    public static void broadcastSlotBreak(org.bukkit.entity.LivingEntity e, org.bukkit.inventory.EquipmentSlot a0) { Shim.onEntity(e, () -> e.broadcastSlotBreak(a0)); }
    public static void broadcastSlotBreak(org.bukkit.entity.LivingEntity e, org.bukkit.inventory.EquipmentSlot a0, java.util.Collection a1) { Shim.onEntity(e, () -> e.broadcastSlotBreak(a0, a1)); }
    public static boolean canBreakDoors(org.bukkit.entity.Zombie e) { if (Shim.ownsEntity(e)) return e.canBreakDoors(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canBreakDoors()); return true; }
    public static boolean canBreatheUnderwater(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.canBreatheUnderwater(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canBreatheUnderwater()); return true; }
    public static boolean canDig(org.bukkit.entity.Sniffer e) { if (Shim.ownsEntity(e)) return e.canDig(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canDig()); return true; }
    public static boolean canDrinkMilk(org.bukkit.entity.WanderingTrader e) { if (Shim.ownsEntity(e)) return e.canDrinkMilk(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canDrinkMilk()); return true; }
    public static boolean canDrinkPotion(org.bukkit.entity.WanderingTrader e) { if (Shim.ownsEntity(e)) return e.canDrinkPotion(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canDrinkPotion()); return true; }
    public static boolean canDuplicate(org.bukkit.entity.Allay e) { if (Shim.ownsEntity(e)) return e.canDuplicate(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canDuplicate()); return true; }
    public static boolean canHitEntity(org.bukkit.entity.Projectile e, org.bukkit.entity.Entity a0) { if (Shim.ownsEntity(e)) return e.canHitEntity(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.canHitEntity(a0)); return true; }
    public static boolean canHurtEntities(org.bukkit.entity.FallingBlock e) { if (Shim.ownsEntity(e)) return e.canHurtEntities(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canHurtEntities()); return true; }
    public static boolean canMobPickup(org.bukkit.entity.Item e) { if (Shim.ownsEntity(e)) return e.canMobPickup(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canMobPickup()); return true; }
    public static boolean canMove(org.bukkit.entity.ArmorStand e) { if (Shim.ownsEntity(e)) return e.canMove(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canMove()); return true; }
    public static boolean canPlayerPickup(org.bukkit.entity.Item e) { if (Shim.ownsEntity(e)) return e.canPlayerPickup(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canPlayerPickup()); return true; }
    public static boolean canTick(org.bukkit.entity.ArmorStand e) { if (Shim.ownsEntity(e)) return e.canTick(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canTick()); return true; }
    public static boolean canTravelThroughPortals(org.bukkit.entity.Wither e) { if (Shim.ownsEntity(e)) return e.canTravelThroughPortals(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canTravelThroughPortals()); return true; }
    public static boolean canUseEquipmentSlot(org.bukkit.entity.LivingEntity e, org.bukkit.inventory.EquipmentSlot a0) { if (Shim.ownsEntity(e)) return e.canUseEquipmentSlot(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.canUseEquipmentSlot(a0)); return true; }
    public static boolean canWander(org.bukkit.entity.Slime e) { if (Shim.ownsEntity(e)) return e.canWander(); ShimCore.ownScheduler().runAtEntity(e, t -> e.canWander()); return true; }
    public static void clearActiveItem(org.bukkit.entity.LivingEntity e) { Shim.onEntity(e, () -> e.clearActiveItem()); }
    public static boolean clearActivePotionEffects(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.clearActivePotionEffects(); ShimCore.ownScheduler().runAtEntity(e, t -> e.clearActivePotionEffects()); return true; }
    public static void clearAnger(org.bukkit.entity.Warden e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.clearAnger(a0)); }
    public static void clearCustomEffects(org.bukkit.entity.AreaEffectCloud e) { Shim.onEntity(e, () -> e.clearCustomEffects()); }
    public static void clearEffectsForNextStew(org.bukkit.entity.MushroomCow e) { Shim.onEntity(e, () -> e.clearEffectsForNextStew()); }
    public static void clearReputations(org.bukkit.entity.Villager e) { Shim.onEntity(e, () -> e.clearReputations()); }
    public static void closeInventory(org.bukkit.entity.HumanEntity e, org.bukkit.event.inventory.InventoryCloseEvent.Reason a0) { Shim.onEntity(e, () -> e.closeInventory(a0)); }
    public static boolean collidesAt(org.bukkit.entity.Entity e, org.bukkit.Location a0) { if (Shim.ownsEntity(e)) return e.collidesAt(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.collidesAt(a0)); return true; }
    public static void completeUsingActiveItem(org.bukkit.entity.LivingEntity e) { Shim.onEntity(e, () -> e.completeUsingActiveItem()); }
    public static void damageItemStack(org.bukkit.entity.LivingEntity e, org.bukkit.inventory.EquipmentSlot a0, int a1) { Shim.onEntity(e, () -> e.damageItemStack(a0, a1)); }
    public static void deactivate(org.bukkit.entity.Creaking e) { Shim.onEntity(e, () -> e.deactivate()); }
    public static boolean doesAutoExpire(org.bukkit.entity.FallingBlock e) { if (Shim.ownsEntity(e)) return e.doesAutoExpire(); ShimCore.ownScheduler().runAtEntity(e, t -> e.doesAutoExpire()); return true; }
    public static boolean dropItem(org.bukkit.entity.HumanEntity e, boolean a0) { if (Shim.ownsEntity(e)) return e.dropItem(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.dropItem(a0)); return true; }
    public static boolean eject(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.eject(); ShimCore.ownScheduler().runAtEntity(e, t -> e.eject()); return true; }
    public static void enterInvulnerabilityPhase(org.bukkit.entity.Wither e) { Shim.onEntity(e, () -> e.enterInvulnerabilityPhase()); }
    public static void explode(org.bukkit.entity.Creeper e) { Shim.onEntity(e, () -> e.explode()); }
    public static boolean fromMobSpawner(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.fromMobSpawner(); ShimCore.ownScheduler().runAtEntity(e, t -> e.fromMobSpawner()); return true; }
    public static boolean getAgeLock(org.bukkit.entity.Tadpole e) { if (Shim.ownsEntity(e)) return e.getAgeLock(); ShimCore.ownScheduler().runAtEntity(e, t -> e.getAgeLock()); return true; }
    public static boolean getApplyLure(org.bukkit.entity.FishHook e) { if (Shim.ownsEntity(e)) return e.getApplyLure(); ShimCore.ownScheduler().runAtEntity(e, t -> e.getApplyLure()); return true; }
    public static boolean getCanPickupItems(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.getCanPickupItems(); ShimCore.ownScheduler().runAtEntity(e, t -> e.getCanPickupItems()); return true; }
    public static boolean getCancelDrop(org.bukkit.entity.FallingBlock e) { if (Shim.ownsEntity(e)) return e.getCancelDrop(); ShimCore.ownScheduler().runAtEntity(e, t -> e.getCancelDrop()); return true; }
    public static boolean getDropItem(org.bukkit.entity.EnderSignal e) { if (Shim.ownsEntity(e)) return e.getDropItem(); ShimCore.ownScheduler().runAtEntity(e, t -> e.getDropItem()); return true; }
    public static boolean getRemoveWhenFarAway(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.getRemoveWhenFarAway(); ShimCore.ownScheduler().runAtEntity(e, t -> e.getRemoveWhenFarAway()); return true; }
    public static boolean getWorkOnLand(org.bukkit.entity.Boat e) { if (Shim.ownsEntity(e)) return e.getWorkOnLand(); ShimCore.ownScheduler().runAtEntity(e, t -> e.getWorkOnLand()); return true; }
    public static boolean hasAI(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.hasAI(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasAI()); return true; }
    public static boolean hasActiveItem(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.hasActiveItem(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasActiveItem()); return true; }
    public static boolean hasArms(org.bukkit.entity.ArmorStand e) { if (Shim.ownsEntity(e)) return e.hasArms(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasArms()); return true; }
    public static boolean hasBasePlate(org.bukkit.entity.ArmorStand e) { if (Shim.ownsEntity(e)) return e.hasBasePlate(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasBasePlate()); return true; }
    public static boolean hasBeenShot(org.bukkit.entity.Projectile e) { if (Shim.ownsEntity(e)) return e.hasBeenShot(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasBeenShot()); return true; }
    public static boolean hasBeenStaredAt(org.bukkit.entity.Enderman e) { if (Shim.ownsEntity(e)) return e.hasBeenStaredAt(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasBeenStaredAt()); return true; }
    public static boolean hasCaravanTail(org.bukkit.entity.Llama e) { if (Shim.ownsEntity(e)) return e.hasCaravanTail(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasCaravanTail()); return true; }
    public static boolean hasCooldown(org.bukkit.entity.HumanEntity e, org.bukkit.inventory.ItemStack a0) { if (Shim.ownsEntity(e)) return e.hasCooldown(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasCooldown(a0)); return true; }
    public static boolean hasCustomEffect(org.bukkit.entity.Arrow e, org.bukkit.potion.PotionEffectType a0) { if (Shim.ownsEntity(e)) return e.hasCustomEffect(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasCustomEffect(a0)); return true; }
    public static boolean hasCustomEffects(org.bukkit.entity.AreaEffectCloud e) { if (Shim.ownsEntity(e)) return e.hasCustomEffects(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasCustomEffects()); return true; }
    public static boolean hasDealtDamage(org.bukkit.entity.Trident e) { if (Shim.ownsEntity(e)) return e.hasDealtDamage(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasDealtDamage()); return true; }
    public static boolean hasEffectForNextStew(org.bukkit.entity.MushroomCow e, org.bukkit.potion.PotionEffectType a0) { if (Shim.ownsEntity(e)) return e.hasEffectForNextStew(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasEffectForNextStew(a0)); return true; }
    public static boolean hasEffectsForNextStew(org.bukkit.entity.MushroomCow e) { if (Shim.ownsEntity(e)) return e.hasEffectsForNextStew(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasEffectsForNextStew()); return true; }
    public static boolean hasEgg(org.bukkit.entity.Turtle e) { if (Shim.ownsEntity(e)) return e.hasEgg(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasEgg()); return true; }
    public static boolean hasEquipmentLock(org.bukkit.entity.ArmorStand e, org.bukkit.inventory.EquipmentSlot a0, org.bukkit.entity.ArmorStand.LockType a1) { if (Shim.ownsEntity(e)) return e.hasEquipmentLock(a0, a1); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasEquipmentLock(a0, a1)); return true; }
    public static boolean hasFish(org.bukkit.entity.Dolphin e) { if (Shim.ownsEntity(e)) return e.hasFish(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasFish()); return true; }
    public static boolean hasFixedPose(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.hasFixedPose(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasFixedPose()); return true; }
    public static boolean hasGlint(org.bukkit.entity.Trident e) { if (Shim.ownsEntity(e)) return e.hasGlint(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasGlint()); return true; }
    public static boolean hasGravity(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.hasGravity(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasGravity()); return true; }
    public static boolean hasLaser(org.bukkit.entity.Guardian e) { if (Shim.ownsEntity(e)) return e.hasLaser(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasLaser()); return true; }
    public static boolean hasLeftHorn(org.bukkit.entity.Goat e) { if (Shim.ownsEntity(e)) return e.hasLeftHorn(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasLeftHorn()); return true; }
    public static boolean hasLeftShooter(org.bukkit.entity.Projectile e) { if (Shim.ownsEntity(e)) return e.hasLeftShooter(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasLeftShooter()); return true; }
    public static boolean hasLimitedLife(org.bukkit.entity.Vex e) { if (Shim.ownsEntity(e)) return e.hasLimitedLife(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasLimitedLife()); return true; }
    public static boolean hasLimitedLifetime(org.bukkit.entity.Vex e) { if (Shim.ownsEntity(e)) return e.hasLimitedLifetime(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasLimitedLifetime()); return true; }
    public static boolean hasLineOfSight(org.bukkit.entity.LivingEntity e, org.bukkit.Location a0) { if (Shim.ownsEntity(e)) return e.hasLineOfSight(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasLineOfSight(a0)); return true; }
    public static boolean hasLineOfSight(org.bukkit.entity.LivingEntity e, org.bukkit.entity.Entity a0) { if (Shim.ownsEntity(e)) return e.hasLineOfSight(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasLineOfSight(a0)); return true; }
    public static boolean hasNectar(org.bukkit.entity.Bee e) { if (Shim.ownsEntity(e)) return e.hasNectar(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasNectar()); return true; }
    public static boolean hasNoPhysics(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.hasNoPhysics(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasNoPhysics()); return true; }
    public static boolean hasPotionEffect(org.bukkit.entity.LivingEntity e, org.bukkit.potion.PotionEffectType a0) { if (Shim.ownsEntity(e)) return e.hasPotionEffect(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasPotionEffect(a0)); return true; }
    public static boolean hasRightHorn(org.bukkit.entity.Goat e) { if (Shim.ownsEntity(e)) return e.hasRightHorn(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasRightHorn()); return true; }
    public static boolean hasSaddle(org.bukkit.entity.Steerable e) { if (Shim.ownsEntity(e)) return e.hasSaddle(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasSaddle()); return true; }
    public static boolean hasStung(org.bukkit.entity.Bee e) { if (Shim.ownsEntity(e)) return e.hasStung(); ShimCore.ownScheduler().runAtEntity(e, t -> e.hasStung()); return true; }
    public static void heal(org.bukkit.entity.Damageable e, double a0, org.bukkit.event.entity.EntityRegainHealthEvent.RegainReason a1) { Shim.onEntity(e, () -> e.heal(a0, a1)); }
    public static void hitEntity(org.bukkit.entity.Projectile e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.hitEntity(a0)); }
    public static void hitEntity(org.bukkit.entity.Projectile e, org.bukkit.entity.Entity a0, org.bukkit.util.Vector a1) { Shim.onEntity(e, () -> e.hitEntity(a0, a1)); }
    public static void ignite(org.bukkit.entity.Creeper e) { Shim.onEntity(e, () -> e.ignite()); }
    public static void ignite(org.bukkit.entity.Creeper e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.ignite(a0)); }
    public static boolean inCaravan(org.bukkit.entity.Llama e) { if (Shim.ownsEntity(e)) return e.inCaravan(); ShimCore.ownScheduler().runAtEntity(e, t -> e.inCaravan()); return true; }
    public static void increaseAnger(org.bukkit.entity.Warden e, org.bukkit.entity.Entity a0, int a1) { Shim.onEntity(e, () -> e.increaseAnger(a0, a1)); }
    public static boolean increaseLevel(org.bukkit.entity.Villager e, int a0) { if (Shim.ownsEntity(e)) return e.increaseLevel(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.increaseLevel(a0)); return true; }
    public static boolean isAbleToBeHunted(org.bukkit.entity.Hoglin e) { if (Shim.ownsEntity(e)) return e.isAbleToBeHunted(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isAbleToBeHunted()); return true; }
    public static boolean isAbleToHunt(org.bukkit.entity.Piglin e) { if (Shim.ownsEntity(e)) return e.isAbleToHunt(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isAbleToHunt()); return true; }
    public static boolean isActive(org.bukkit.entity.Creaking e) { if (Shim.ownsEntity(e)) return e.isActive(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isActive()); return true; }
    public static boolean isAdult(org.bukkit.entity.Ageable e) { if (Shim.ownsEntity(e)) return e.isAdult(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isAdult()); return true; }
    public static boolean isAggressive(org.bukkit.entity.Mob e) { if (Shim.ownsEntity(e)) return e.isAggressive(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isAggressive()); return true; }
    public static boolean isAngry(org.bukkit.entity.Wolf e) { if (Shim.ownsEntity(e)) return e.isAngry(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isAngry()); return true; }
    public static boolean isArmsRaised(org.bukkit.entity.Zombie e) { if (Shim.ownsEntity(e)) return e.isArmsRaised(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isArmsRaised()); return true; }
    public static boolean isAwake(org.bukkit.entity.Bat e) { if (Shim.ownsEntity(e)) return e.isAwake(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isAwake()); return true; }
    public static boolean isAware(org.bukkit.entity.Mob e) { if (Shim.ownsEntity(e)) return e.isAware(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isAware()); return true; }
    public static boolean isBaby(org.bukkit.entity.PiglinAbstract e) { if (Shim.ownsEntity(e)) return e.isBaby(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isBaby()); return true; }
    public static boolean isBlocking(org.bukkit.entity.HumanEntity e) { if (Shim.ownsEntity(e)) return e.isBlocking(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isBlocking()); return true; }
    public static boolean isBreedItem(org.bukkit.entity.Animals e, org.bukkit.inventory.ItemStack a0) { if (Shim.ownsEntity(e)) return e.isBreedItem(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.isBreedItem(a0)); return true; }
    public static boolean isCanJoinRaid(org.bukkit.entity.Raider e) { if (Shim.ownsEntity(e)) return e.isCanJoinRaid(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isCanJoinRaid()); return true; }
    public static boolean isCarryingChest(org.bukkit.entity.ChestedHorse e) { if (Shim.ownsEntity(e)) return e.isCarryingChest(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isCarryingChest()); return true; }
    public static boolean isCelebrating(org.bukkit.entity.Raider e) { if (Shim.ownsEntity(e)) return e.isCelebrating(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isCelebrating()); return true; }
    public static boolean isCharged(org.bukkit.entity.WitherSkull e) { if (Shim.ownsEntity(e)) return e.isCharged(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isCharged()); return true; }
    public static boolean isCharging(org.bukkit.entity.Vex e) { if (Shim.ownsEntity(e)) return e.isCharging(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isCharging()); return true; }
    public static boolean isChargingCrossbow(org.bukkit.entity.Piglin e) { if (Shim.ownsEntity(e)) return e.isChargingCrossbow(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isChargingCrossbow()); return true; }
    public static boolean isChickenJockey(org.bukkit.entity.Chicken e) { if (Shim.ownsEntity(e)) return e.isChickenJockey(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isChickenJockey()); return true; }
    public static boolean isClimbing(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.isClimbing(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isClimbing()); return true; }
    public static boolean isCollidable(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.isCollidable(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isCollidable()); return true; }
    public static boolean isConverting(org.bukkit.entity.PiglinAbstract e) { if (Shim.ownsEntity(e)) return e.isConverting(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isConverting()); return true; }
    public static boolean isCritical(org.bukkit.entity.AbstractArrow e) { if (Shim.ownsEntity(e)) return e.isCritical(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isCritical()); return true; }
    public static boolean isCrouching(org.bukkit.entity.Fox e) { if (Shim.ownsEntity(e)) return e.isCrouching(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isCrouching()); return true; }
    public static boolean isCustomNameVisible(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isCustomNameVisible(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isCustomNameVisible()); return true; }
    public static boolean isDancing(org.bukkit.entity.Parrot e) { if (Shim.ownsEntity(e)) return e.isDancing(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isDancing()); return true; }
    public static boolean isDashing(org.bukkit.entity.Camel e) { if (Shim.ownsEntity(e)) return e.isDashing(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isDashing()); return true; }
    public static boolean isDeeplySleeping(org.bukkit.entity.HumanEntity e) { if (Shim.ownsEntity(e)) return e.isDeeplySleeping(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isDeeplySleeping()); return true; }
    public static boolean isDefending(org.bukkit.entity.Fox e) { if (Shim.ownsEntity(e)) return e.isDefending(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isDefending()); return true; }
    public static boolean isDerp(org.bukkit.entity.Snowman e) { if (Shim.ownsEntity(e)) return e.isDerp(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isDerp()); return true; }
    public static boolean isDetonated(org.bukkit.entity.Firework e) { if (Shim.ownsEntity(e)) return e.isDetonated(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isDetonated()); return true; }
    public static boolean isDrinkingPotion(org.bukkit.entity.Witch e) { if (Shim.ownsEntity(e)) return e.isDrinkingPotion(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isDrinkingPotion()); return true; }
    public static boolean isDrowning(org.bukkit.entity.Zombie e) { if (Shim.ownsEntity(e)) return e.isDrowning(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isDrowning()); return true; }
    public static boolean isEating(org.bukkit.entity.Panda e) { if (Shim.ownsEntity(e)) return e.isEating(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isEating()); return true; }
    public static boolean isEatingGrass(org.bukkit.entity.AbstractHorse e) { if (Shim.ownsEntity(e)) return e.isEatingGrass(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isEatingGrass()); return true; }
    public static boolean isEatingHaystack(org.bukkit.entity.AbstractHorse e) { if (Shim.ownsEntity(e)) return e.isEatingHaystack(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isEatingHaystack()); return true; }
    public static boolean isEffect(org.bukkit.entity.LightningStrike e) { if (Shim.ownsEntity(e)) return e.isEffect(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isEffect()); return true; }
    public static boolean isEmpty(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isEmpty(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isEmpty()); return true; }
    public static boolean isFaceplanted(org.bukkit.entity.Fox e) { if (Shim.ownsEntity(e)) return e.isFaceplanted(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isFaceplanted()); return true; }
    public static boolean isFixed(org.bukkit.entity.ItemFrame e) { if (Shim.ownsEntity(e)) return e.isFixed(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isFixed()); return true; }
    public static boolean isFrozen(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isFrozen(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isFrozen()); return true; }
    public static boolean isGliding(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.isGliding(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isGliding()); return true; }
    public static boolean isGlowing(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isGlowing(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isGlowing()); return true; }
    public static boolean isGoingHome(org.bukkit.entity.Turtle e) { if (Shim.ownsEntity(e)) return e.isGoingHome(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isGoingHome()); return true; }
    public static boolean isHandRaised(org.bukkit.entity.HumanEntity e) { if (Shim.ownsEntity(e)) return e.isHandRaised(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isHandRaised()); return true; }
    public static boolean isHeadUp(org.bukkit.entity.Cat e) { if (Shim.ownsEntity(e)) return e.isHeadUp(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isHeadUp()); return true; }
    public static boolean isIgnited(org.bukkit.entity.Creeper e) { if (Shim.ownsEntity(e)) return e.isIgnited(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isIgnited()); return true; }
    public static boolean isImmuneToZombification(org.bukkit.entity.Hoglin e) { if (Shim.ownsEntity(e)) return e.isImmuneToZombification(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isImmuneToZombification()); return true; }
    public static boolean isInBlock(org.bukkit.entity.AbstractArrow e) { if (Shim.ownsEntity(e)) return e.isInBlock(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isInBlock()); return true; }
    public static boolean isInDaylight(org.bukkit.entity.Mob e) { if (Shim.ownsEntity(e)) return e.isInDaylight(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isInDaylight()); return true; }
    public static boolean isInLava(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isInLava(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isInLava()); return true; }
    public static boolean isInOpenWater(org.bukkit.entity.FishHook e) { if (Shim.ownsEntity(e)) return e.isInOpenWater(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isInOpenWater()); return true; }
    public static boolean isInPowderedSnow(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isInPowderedSnow(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isInPowderedSnow()); return true; }
    public static boolean isInRain(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isInRain(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isInRain()); return true; }
    public static boolean isInWorld(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isInWorld(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isInWorld()); return true; }
    public static boolean isIncendiary(org.bukkit.entity.Explosive e) { if (Shim.ownsEntity(e)) return e.isIncendiary(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isIncendiary()); return true; }
    public static boolean isInsideVehicle(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isInsideVehicle(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isInsideVehicle()); return true; }
    public static boolean isInterested(org.bukkit.entity.Fox e) { if (Shim.ownsEntity(e)) return e.isInterested(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isInterested()); return true; }
    public static boolean isInvisible(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isInvisible(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isInvisible()); return true; }
    public static boolean isInvulnerable(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isInvulnerable(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isInvulnerable()); return true; }
    public static boolean isJohnny(org.bukkit.entity.Vindicator e) { if (Shim.ownsEntity(e)) return e.isJohnny(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isJohnny()); return true; }
    public static boolean isJumping(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.isJumping(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isJumping()); return true; }
    public static boolean isLayingEgg(org.bukkit.entity.Turtle e) { if (Shim.ownsEntity(e)) return e.isLayingEgg(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isLayingEgg()); return true; }
    public static boolean isLeaping(org.bukkit.entity.Fox e) { if (Shim.ownsEntity(e)) return e.isLeaping(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isLeaping()); return true; }
    public static boolean isLeftHanded(org.bukkit.entity.Mob e) { if (Shim.ownsEntity(e)) return e.isLeftHanded(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isLeftHanded()); return true; }
    public static boolean isLoveMode(org.bukkit.entity.Animals e) { if (Shim.ownsEntity(e)) return e.isLoveMode(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isLoveMode()); return true; }
    public static boolean isLyingDown(org.bukkit.entity.Cat e) { if (Shim.ownsEntity(e)) return e.isLyingDown(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isLyingDown()); return true; }
    public static boolean isMarker(org.bukkit.entity.ArmorStand e) { if (Shim.ownsEntity(e)) return e.isMarker(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isMarker()); return true; }
    public static boolean isMoving(org.bukkit.entity.Guardian e) { if (Shim.ownsEntity(e)) return e.isMoving(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isMoving()); return true; }
    public static boolean isOnBack(org.bukkit.entity.Panda e) { if (Shim.ownsEntity(e)) return e.isOnBack(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isOnBack()); return true; }
    public static boolean isPatrolLeader(org.bukkit.entity.Raider e) { if (Shim.ownsEntity(e)) return e.isPatrolLeader(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isPatrolLeader()); return true; }
    public static boolean isPlayerCreated(org.bukkit.entity.IronGolem e) { if (Shim.ownsEntity(e)) return e.isPlayerCreated(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isPlayerCreated()); return true; }
    public static boolean isPlayingDead(org.bukkit.entity.Axolotl e) { if (Shim.ownsEntity(e)) return e.isPlayingDead(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isPlayingDead()); return true; }
    public static boolean isPowered(org.bukkit.entity.Creeper e) { if (Shim.ownsEntity(e)) return e.isPowered(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isPowered()); return true; }
    public static boolean isRainInfluenced(org.bukkit.entity.FishHook e) { if (Shim.ownsEntity(e)) return e.isRainInfluenced(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isRainInfluenced()); return true; }
    public static boolean isRearing(org.bukkit.entity.AbstractHorse e) { if (Shim.ownsEntity(e)) return e.isRearing(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isRearing()); return true; }
    public static boolean isResponsive(org.bukkit.entity.Interaction e) { if (Shim.ownsEntity(e)) return e.isResponsive(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isResponsive()); return true; }
    public static boolean isRiptiding(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.isRiptiding(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isRiptiding()); return true; }
    public static boolean isRolling(org.bukkit.entity.Bee e) { if (Shim.ownsEntity(e)) return e.isRolling(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isRolling()); return true; }
    public static boolean isScared(org.bukkit.entity.Panda e) { if (Shim.ownsEntity(e)) return e.isScared(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isScared()); return true; }
    public static boolean isScreaming(org.bukkit.entity.Enderman e) { if (Shim.ownsEntity(e)) return e.isScreaming(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isScreaming()); return true; }
    public static boolean isSheared(org.bukkit.entity.Sheep e) { if (Shim.ownsEntity(e)) return e.isSheared(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isSheared()); return true; }
    public static boolean isShivering(org.bukkit.entity.Strider e) { if (Shim.ownsEntity(e)) return e.isShivering(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isShivering()); return true; }
    public static boolean isShotAtAngle(org.bukkit.entity.Firework e) { if (Shim.ownsEntity(e)) return e.isShotAtAngle(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isShotAtAngle()); return true; }
    public static boolean isShotFromCrossbow(org.bukkit.entity.AbstractArrow e) { if (Shim.ownsEntity(e)) return e.isShotFromCrossbow(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isShotFromCrossbow()); return true; }
    public static boolean isShowingBottom(org.bukkit.entity.EnderCrystal e) { if (Shim.ownsEntity(e)) return e.isShowingBottom(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isShowingBottom()); return true; }
    public static boolean isSilent(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isSilent(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isSilent()); return true; }
    public static boolean isSitting(org.bukkit.entity.Sittable e) { if (Shim.ownsEntity(e)) return e.isSitting(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isSitting()); return true; }
    public static boolean isSkyInfluenced(org.bukkit.entity.FishHook e) { if (Shim.ownsEntity(e)) return e.isSkyInfluenced(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isSkyInfluenced()); return true; }
    public static boolean isSleeping(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.isSleeping(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isSleeping()); return true; }
    public static boolean isSlotDisabled(org.bukkit.entity.ArmorStand e, org.bukkit.inventory.EquipmentSlot a0) { if (Shim.ownsEntity(e)) return e.isSlotDisabled(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.isSlotDisabled(a0)); return true; }
    public static boolean isSlowWhenEmpty(org.bukkit.entity.Minecart e) { if (Shim.ownsEntity(e)) return e.isSlowWhenEmpty(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isSlowWhenEmpty()); return true; }
    public static boolean isSmall(org.bukkit.entity.ArmorStand e) { if (Shim.ownsEntity(e)) return e.isSmall(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isSmall()); return true; }
    public static boolean isSneaking(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isSneaking(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isSneaking()); return true; }
    public static boolean isSneezing(org.bukkit.entity.Panda e) { if (Shim.ownsEntity(e)) return e.isSneezing(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isSneezing()); return true; }
    public static boolean isStanding(org.bukkit.entity.PolarBear e) { if (Shim.ownsEntity(e)) return e.isStanding(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isStanding()); return true; }
    public static boolean isSwimming(org.bukkit.entity.LivingEntity e) { if (Shim.ownsEntity(e)) return e.isSwimming(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isSwimming()); return true; }
    public static boolean isTamed(org.bukkit.entity.Tameable e) { if (Shim.ownsEntity(e)) return e.isTamed(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isTamed()); return true; }
    public static boolean isTicking(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isTicking(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isTicking()); return true; }
    public static boolean isTrapped(org.bukkit.entity.SkeletonHorse e) { if (Shim.ownsEntity(e)) return e.isTrapped(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isTrapped()); return true; }
    public static boolean isTrusting(org.bukkit.entity.Ocelot e) { if (Shim.ownsEntity(e)) return e.isTrusting(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isTrusting()); return true; }
    public static boolean isUnderWater(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isUnderWater(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isUnderWater()); return true; }
    public static boolean isUnlimitedLifetime(org.bukkit.entity.Item e) { if (Shim.ownsEntity(e)) return e.isUnlimitedLifetime(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isUnlimitedLifetime()); return true; }
    public static boolean isVillager(org.bukkit.entity.Zombie e) { if (Shim.ownsEntity(e)) return e.isVillager(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isVillager()); return true; }
    public static boolean isVisible(org.bukkit.entity.ItemFrame e) { if (Shim.ownsEntity(e)) return e.isVisible(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isVisible()); return true; }
    public static boolean isVisibleByDefault(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.isVisibleByDefault(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isVisibleByDefault()); return true; }
    public static boolean isWet(org.bukkit.entity.Wolf e) { if (Shim.ownsEntity(e)) return e.isWet(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isWet()); return true; }
    public static void joinCaravan(org.bukkit.entity.Llama e, org.bukkit.entity.Llama a0) { Shim.onEntity(e, () -> e.joinCaravan(a0)); }
    public static void knockback(org.bukkit.entity.LivingEntity e, double a0, double a1, double a2) { Shim.onEntity(e, () -> e.knockback(a0, a1, a2)); }
    public static void leaveCaravan(org.bukkit.entity.Llama e) { Shim.onEntity(e, () -> e.leaveCaravan()); }
    public static boolean leaveVehicle(org.bukkit.entity.Entity e) { if (Shim.ownsEntity(e)) return e.leaveVehicle(); ShimCore.ownScheduler().runAtEntity(e, t -> e.leaveVehicle()); return true; }
    public static void lookAt(org.bukkit.entity.Mob e, double a0, double a1, double a2) { Shim.onEntity(e, () -> e.lookAt(a0, a1, a2)); }
    public static void lookAt(org.bukkit.entity.Mob e, double a0, double a1, double a2, float a3, float a4) { Shim.onEntity(e, () -> e.lookAt(a0, a1, a2, a3, a4)); }
    public static void lookAt(org.bukkit.entity.Entity e, double a0, double a1, double a2, io.papermc.paper.entity.LookAnchor a3) { Shim.onEntity(e, () -> e.lookAt(a0, a1, a2, a3)); }
    public static void lookAt(org.bukkit.entity.Mob e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.lookAt(a0)); }
    public static void lookAt(org.bukkit.entity.Mob e, org.bukkit.Location a0, float a1, float a2) { Shim.onEntity(e, () -> e.lookAt(a0, a1, a2)); }
    public static void lookAt(org.bukkit.entity.Mob e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.lookAt(a0)); }
    public static void lookAt(org.bukkit.entity.Mob e, org.bukkit.entity.Entity a0, float a1, float a2) { Shim.onEntity(e, () -> e.lookAt(a0, a1, a2)); }
    public static void lookAt(org.bukkit.entity.Player e, org.bukkit.entity.Entity a0, io.papermc.paper.entity.LookAnchor a1, io.papermc.paper.entity.LookAnchor a2) { Shim.onEntity(e, () -> e.lookAt(a0, a1, a2)); }
    public static void openInventory(org.bukkit.entity.HumanEntity e, org.bukkit.inventory.InventoryView a0) { Shim.onEntity(e, () -> e.openInventory(a0)); }
    public static boolean performCommand(org.bukkit.entity.Player e, java.lang.String a0) { if (Shim.ownsEntity(e)) return e.performCommand(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.performCommand(a0)); return true; }
    public static void playEffect(org.bukkit.entity.Entity e, org.bukkit.EntityEffect a0) { Shim.onEntity(e, () -> e.playEffect(a0)); }
    public static void playHurtAnimation(org.bukkit.entity.LivingEntity e, float a0) { Shim.onEntity(e, () -> e.playHurtAnimation(a0)); }
    public static void playPickupItemAnimation(org.bukkit.entity.LivingEntity e, org.bukkit.entity.Item a0, int a1) { Shim.onEntity(e, () -> e.playPickupItemAnimation(a0, a1)); }
    public static void ram(org.bukkit.entity.Goat e, org.bukkit.entity.LivingEntity a0) { Shim.onEntity(e, () -> e.ram(a0)); }
    public static boolean removeBarterMaterial(org.bukkit.entity.Piglin e, org.bukkit.Material a0) { if (Shim.ownsEntity(e)) return e.removeBarterMaterial(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.removeBarterMaterial(a0)); return true; }
    public static boolean removeCustomEffect(org.bukkit.entity.AreaEffectCloud e, org.bukkit.potion.PotionEffectType a0) { if (Shim.ownsEntity(e)) return e.removeCustomEffect(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.removeCustomEffect(a0)); return true; }
    public static boolean removeEffectFromNextStew(org.bukkit.entity.MushroomCow e, org.bukkit.potion.PotionEffectType a0) { if (Shim.ownsEntity(e)) return e.removeEffectFromNextStew(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.removeEffectFromNextStew(a0)); return true; }
    public static void removeEquipmentLock(org.bukkit.entity.ArmorStand e, org.bukkit.inventory.EquipmentSlot a0, org.bukkit.entity.ArmorStand.LockType a1) { Shim.onEntity(e, () -> e.removeEquipmentLock(a0, a1)); }
    public static void removeExploredLocation(org.bukkit.entity.Sniffer e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.removeExploredLocation(a0)); }
    public static boolean removeMaterialOfInterest(org.bukkit.entity.Piglin e, org.bukkit.Material a0) { if (Shim.ownsEntity(e)) return e.removeMaterialOfInterest(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.removeMaterialOfInterest(a0)); return true; }
    public static boolean removePassenger(org.bukkit.entity.Entity e, org.bukkit.entity.Entity a0) { if (Shim.ownsEntity(e)) return e.removePassenger(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.removePassenger(a0)); return true; }
    public static boolean removeScoreboardTag(org.bukkit.entity.Entity e, java.lang.String a0) { if (Shim.ownsEntity(e)) return e.removeScoreboardTag(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.removeScoreboardTag(a0)); return true; }
    public static void resetDuplicationCooldown(org.bukkit.entity.Allay e) { Shim.onEntity(e, () -> e.resetDuplicationCooldown()); }
    public static void resetFishingState(org.bukkit.entity.FishHook e) { Shim.onEntity(e, () -> e.resetFishingState()); }
    public static void resetMaxHealth(org.bukkit.entity.Damageable e) { Shim.onEntity(e, () -> e.resetMaxHealth()); }
    public static void resetOffers(org.bukkit.entity.AbstractVillager e) { Shim.onEntity(e, () -> e.resetOffers()); }
    public static void sendEntityEffect(org.bukkit.entity.Player e, org.bukkit.EntityEffect a0, org.bukkit.entity.Entity a1) { Shim.onEntity(e, () -> e.sendEntityEffect(a0, a1)); }
    public static void setAbsorptionAmount(org.bukkit.entity.Damageable e, double a0) { Shim.onEntity(e, () -> e.setAbsorptionAmount(a0)); }
    public static void setAcceleration(org.bukkit.entity.Fireball e, org.bukkit.util.Vector a0) { Shim.onEntity(e, () -> e.setAcceleration(a0)); }
    public static void setActiveItemRemainingTime(org.bukkit.entity.LivingEntity e, int a0) { Shim.onEntity(e, () -> e.setActiveItemRemainingTime(a0)); }
    public static void setAdult(org.bukkit.entity.Ageable e) { Shim.onEntity(e, () -> e.setAdult()); }
    public static void setAge(org.bukkit.entity.Tadpole e, int a0) { Shim.onEntity(e, () -> e.setAge(a0)); }
    public static void setAgeLock(org.bukkit.entity.Ageable e, boolean a0) { Shim.onEntity(e, () -> e.setAgeLock(a0)); }
    public static void setAggressive(org.bukkit.entity.Mob e, boolean a0) { Shim.onEntity(e, () -> e.setAggressive(a0)); }
    public static void setAnchorLocation(org.bukkit.entity.Phantom e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setAnchorLocation(a0)); }
    public static void setAnger(org.bukkit.entity.Bee e, int a0) { Shim.onEntity(e, () -> e.setAnger(a0)); }
    public static void setAnger(org.bukkit.entity.Warden e, org.bukkit.entity.Entity a0, int a1) { Shim.onEntity(e, () -> e.setAnger(a0, a1)); }
    public static void setAngry(org.bukkit.entity.Wolf e, boolean a0) { Shim.onEntity(e, () -> e.setAngry(a0)); }
    public static void setApplyLure(org.bukkit.entity.FishHook e, boolean a0) { Shim.onEntity(e, () -> e.setApplyLure(a0)); }
    public static void setArms(org.bukkit.entity.ArmorStand e, boolean a0) { Shim.onEntity(e, () -> e.setArms(a0)); }
    public static void setArmsRaised(org.bukkit.entity.Zombie e, boolean a0) { Shim.onEntity(e, () -> e.setArmsRaised(a0)); }
    public static void setArrowCooldown(org.bukkit.entity.LivingEntity e, int a0) { Shim.onEntity(e, () -> e.setArrowCooldown(a0)); }
    public static void setArrowsInBody(org.bukkit.entity.LivingEntity e, int a0, boolean a1) { Shim.onEntity(e, () -> e.setArrowsInBody(a0, a1)); }
    public static boolean setArt(org.bukkit.entity.Painting e, org.bukkit.Art a0, boolean a1) { if (Shim.ownsEntity(e)) return e.setArt(a0, a1); ShimCore.ownScheduler().runAtEntity(e, t -> e.setArt(a0, a1)); return true; }
    public static void setAttachedFace(org.bukkit.entity.Shulker e, org.bukkit.block.BlockFace a0) { Shim.onEntity(e, () -> e.setAttachedFace(a0)); }
    public static boolean setAttachedTo(org.bukkit.entity.Firework e, org.bukkit.entity.LivingEntity a0) { if (Shim.ownsEntity(e)) return e.setAttachedTo(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.setAttachedTo(a0)); return true; }
    public static void setAttackDelay(org.bukkit.entity.EvokerFangs e, int a0) { Shim.onEntity(e, () -> e.setAttackDelay(a0)); }
    public static void setAttackTicks(org.bukkit.entity.Ravager e, int a0) { Shim.onEntity(e, () -> e.setAttackTicks(a0)); }
    public static void setAwake(org.bukkit.entity.Bat e, boolean a0) { Shim.onEntity(e, () -> e.setAwake(a0)); }
    public static void setAware(org.bukkit.entity.Mob e, boolean a0) { Shim.onEntity(e, () -> e.setAware(a0)); }
    public static void setBaby(org.bukkit.entity.Ageable e) { Shim.onEntity(e, () -> e.setBaby()); }
    public static void setBaby(org.bukkit.entity.Zombie e, boolean a0) { Shim.onEntity(e, () -> e.setBaby(a0)); }
    public static void setBackgroundColor(org.bukkit.entity.TextDisplay e, org.bukkit.Color a0) { Shim.onEntity(e, () -> e.setBackgroundColor(a0)); }
    public static void setBasePlate(org.bukkit.entity.ArmorStand e, boolean a0) { Shim.onEntity(e, () -> e.setBasePlate(a0)); }
    public static void setBasePotionType(org.bukkit.entity.AreaEffectCloud e, org.bukkit.potion.PotionType a0) { Shim.onEntity(e, () -> e.setBasePotionType(a0)); }
    public static void setBeamTarget(org.bukkit.entity.EnderCrystal e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setBeamTarget(a0)); }
    public static void setBeeStingerCooldown(org.bukkit.entity.LivingEntity e, int a0) { Shim.onEntity(e, () -> e.setBeeStingerCooldown(a0)); }
    public static void setBeeStingersInBody(org.bukkit.entity.LivingEntity e, int a0) { Shim.onEntity(e, () -> e.setBeeStingersInBody(a0)); }
    public static void setBillboard(org.bukkit.entity.Display e, org.bukkit.entity.Display.Billboard a0) { Shim.onEntity(e, () -> e.setBillboard(a0)); }
    public static void setBlock(org.bukkit.entity.BlockDisplay e, org.bukkit.block.data.BlockData a0) { Shim.onEntity(e, () -> e.setBlock(a0)); }
    public static void setBlockData(org.bukkit.entity.TNTPrimed e, org.bukkit.block.data.BlockData a0) { Shim.onEntity(e, () -> e.setBlockData(a0)); }
    public static void setBlockState(org.bukkit.entity.FallingBlock e, org.bukkit.block.BlockState a0) { Shim.onEntity(e, () -> e.setBlockState(a0)); }
    public static void setBodyColor(org.bukkit.entity.TropicalFish e, org.bukkit.DyeColor a0) { Shim.onEntity(e, () -> e.setBodyColor(a0)); }
    public static void setBodyPose(org.bukkit.entity.ArmorStand e, org.bukkit.util.EulerAngle a0) { Shim.onEntity(e, () -> e.setBodyPose(a0)); }
    public static void setBodyRotations(org.bukkit.entity.ArmorStand e, io.papermc.paper.math.Rotations a0) { Shim.onEntity(e, () -> e.setBodyRotations(a0)); }
    public static void setBodyYaw(org.bukkit.entity.LivingEntity e, float a0) { Shim.onEntity(e, () -> e.setBodyYaw(a0)); }
    public static void setBoostTicks(org.bukkit.entity.Steerable e, int a0) { Shim.onEntity(e, () -> e.setBoostTicks(a0)); }
    public static void setBound(org.bukkit.entity.Vex e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setBound(a0)); }
    public static void setBreedCause(org.bukkit.entity.Animals e, java.util.UUID a0) { Shim.onEntity(e, () -> e.setBreedCause(a0)); }
    public static void setBrightness(org.bukkit.entity.Display e, org.bukkit.entity.Display.Brightness a0) { Shim.onEntity(e, () -> e.setBrightness(a0)); }
    public static void setCanBreakDoors(org.bukkit.entity.Zombie e, boolean a0) { Shim.onEntity(e, () -> e.setCanBreakDoors(a0)); }
    public static void setCanDrinkMilk(org.bukkit.entity.WanderingTrader e, boolean a0) { Shim.onEntity(e, () -> e.setCanDrinkMilk(a0)); }
    public static void setCanDrinkPotion(org.bukkit.entity.WanderingTrader e, boolean a0) { Shim.onEntity(e, () -> e.setCanDrinkPotion(a0)); }
    public static void setCanDuplicate(org.bukkit.entity.Allay e, boolean a0) { Shim.onEntity(e, () -> e.setCanDuplicate(a0)); }
    public static void setCanJoinRaid(org.bukkit.entity.Raider e, boolean a0) { Shim.onEntity(e, () -> e.setCanJoinRaid(a0)); }
    public static void setCanMobPickup(org.bukkit.entity.Item e, boolean a0) { Shim.onEntity(e, () -> e.setCanMobPickup(a0)); }
    public static void setCanMove(org.bukkit.entity.ArmorStand e, boolean a0) { Shim.onEntity(e, () -> e.setCanMove(a0)); }
    public static void setCanPickupItems(org.bukkit.entity.LivingEntity e, boolean a0) { Shim.onEntity(e, () -> e.setCanPickupItems(a0)); }
    public static void setCanPlayerPickup(org.bukkit.entity.Item e, boolean a0) { Shim.onEntity(e, () -> e.setCanPlayerPickup(a0)); }
    public static void setCanTick(org.bukkit.entity.ArmorStand e, boolean a0) { Shim.onEntity(e, () -> e.setCanTick(a0)); }
    public static void setCanTravelThroughPortals(org.bukkit.entity.Wither e, boolean a0) { Shim.onEntity(e, () -> e.setCanTravelThroughPortals(a0)); }
    public static void setCancelDrop(org.bukkit.entity.FallingBlock e, boolean a0) { Shim.onEntity(e, () -> e.setCancelDrop(a0)); }
    public static void setCannotEnterHiveTicks(org.bukkit.entity.Bee e, int a0) { Shim.onEntity(e, () -> e.setCannotEnterHiveTicks(a0)); }
    public static void setCarriedBlock(org.bukkit.entity.Enderman e, org.bukkit.block.data.BlockData a0) { Shim.onEntity(e, () -> e.setCarriedBlock(a0)); }
    public static void setCarriedMaterial(org.bukkit.entity.Enderman e, org.bukkit.material.MaterialData a0) { Shim.onEntity(e, () -> e.setCarriedMaterial(a0)); }
    public static void setCarryingChest(org.bukkit.entity.ChestedHorse e, boolean a0) { Shim.onEntity(e, () -> e.setCarryingChest(a0)); }
    public static void setCatType(org.bukkit.entity.Cat e, org.bukkit.entity.Cat.Type a0) { Shim.onEntity(e, () -> e.setCatType(a0)); }
    public static void setCausingPlayer(org.bukkit.entity.LightningStrike e, org.bukkit.entity.Player a0) { Shim.onEntity(e, () -> e.setCausingPlayer(a0)); }
    public static void setCelebrating(org.bukkit.entity.Raider e, boolean a0) { Shim.onEntity(e, () -> e.setCelebrating(a0)); }
    public static void setCharged(org.bukkit.entity.WitherSkull e, boolean a0) { Shim.onEntity(e, () -> e.setCharged(a0)); }
    public static void setCharging(org.bukkit.entity.Ghast e, boolean a0) { Shim.onEntity(e, () -> e.setCharging(a0)); }
    public static void setChargingCrossbow(org.bukkit.entity.Piglin e, boolean a0) { Shim.onEntity(e, () -> e.setChargingCrossbow(a0)); }
    public static void setCollarColor(org.bukkit.entity.Wolf e, org.bukkit.DyeColor a0) { Shim.onEntity(e, () -> e.setCollarColor(a0)); }
    public static void setColor(org.bukkit.entity.AreaEffectCloud e, org.bukkit.Color a0) { Shim.onEntity(e, () -> e.setColor(a0)); }
    public static void setColor(org.bukkit.entity.Horse e, org.bukkit.entity.Horse.Color a0) { Shim.onEntity(e, () -> e.setColor(a0)); }
    public static void setColor(org.bukkit.entity.Llama e, org.bukkit.entity.Llama.Color a0) { Shim.onEntity(e, () -> e.setColor(a0)); }
    public static void setConversionPlayer(org.bukkit.entity.ZombieVillager e, org.bukkit.OfflinePlayer a0) { Shim.onEntity(e, () -> e.setConversionPlayer(a0)); }
    public static void setConversionTime(org.bukkit.entity.Skeleton e, int a0) { Shim.onEntity(e, () -> e.setConversionTime(a0)); }
    public static void setConversionTime(org.bukkit.entity.ZombieVillager e, int a0, boolean a1) { Shim.onEntity(e, () -> e.setConversionTime(a0, a1)); }
    public static void setCooldown(org.bukkit.entity.HumanEntity e, org.bukkit.inventory.ItemStack a0, int a1) { Shim.onEntity(e, () -> e.setCooldown(a0, a1)); }
    public static void setCount(org.bukkit.entity.ExperienceOrb e, int a0) { Shim.onEntity(e, () -> e.setCount(a0)); }
    public static void setCritical(org.bukkit.entity.AbstractArrow e, boolean a0) { Shim.onEntity(e, () -> e.setCritical(a0)); }
    public static void setCropsGrownSincePollination(org.bukkit.entity.Bee e, int a0) { Shim.onEntity(e, () -> e.setCropsGrownSincePollination(a0)); }
    public static void setCrouching(org.bukkit.entity.Fox e, boolean a0) { Shim.onEntity(e, () -> e.setCrouching(a0)); }
    public static void setCurrentBoostTicks(org.bukkit.entity.Steerable e, int a0) { Shim.onEntity(e, () -> e.setCurrentBoostTicks(a0)); }
    public static void setCurrentMovementDirection(org.bukkit.entity.ShulkerBullet e, org.bukkit.block.BlockFace a0) { Shim.onEntity(e, () -> e.setCurrentMovementDirection(a0)); }
    public static void setCurrentSpell(org.bukkit.entity.Evoker e, org.bukkit.entity.Evoker.Spell a0) { Shim.onEntity(e, () -> e.setCurrentSpell(a0)); }
    public static void setDamage(org.bukkit.entity.Minecart e, double a0) { Shim.onEntity(e, () -> e.setDamage(a0)); }
    public static void setDamagePerBlock(org.bukkit.entity.FallingBlock e, float a0) { Shim.onEntity(e, () -> e.setDamagePerBlock(a0)); }
    public static void setDancing(org.bukkit.entity.Piglin e, long a0) { Shim.onEntity(e, () -> e.setDancing(a0)); }
    public static void setDancing(org.bukkit.entity.Piglin e, boolean a0) { Shim.onEntity(e, () -> e.setDancing(a0)); }
    public static void setDarkTicksRemaining(org.bukkit.entity.GlowSquid e, int a0) { Shim.onEntity(e, () -> e.setDarkTicksRemaining(a0)); }
    public static void setDashing(org.bukkit.entity.Camel e, boolean a0) { Shim.onEntity(e, () -> e.setDashing(a0)); }
    public static void setDefending(org.bukkit.entity.Fox e, boolean a0) { Shim.onEntity(e, () -> e.setDefending(a0)); }
    public static void setDerailedVelocityMod(org.bukkit.entity.Minecart e, org.bukkit.util.Vector a0) { Shim.onEntity(e, () -> e.setDerailedVelocityMod(a0)); }
    public static void setDerp(org.bukkit.entity.Snowman e, boolean a0) { Shim.onEntity(e, () -> e.setDerp(a0)); }
    public static void setDespawnDelay(org.bukkit.entity.WanderingTrader e, int a0) { Shim.onEntity(e, () -> e.setDespawnDelay(a0)); }
    public static void setDespawnTimer(org.bukkit.entity.EnderSignal e, int a0) { Shim.onEntity(e, () -> e.setDespawnTimer(a0)); }
    public static void setDisabledSlots(org.bukkit.entity.ArmorStand e, org.bukkit.inventory.EquipmentSlot[] a0) { Shim.onEntity(e, () -> e.setDisabledSlots(a0)); }
    public static void setDisplayBlock(org.bukkit.entity.Minecart e, org.bukkit.material.MaterialData a0) { Shim.onEntity(e, () -> e.setDisplayBlock(a0)); }
    public static void setDisplayBlockData(org.bukkit.entity.Minecart e, org.bukkit.block.data.BlockData a0) { Shim.onEntity(e, () -> e.setDisplayBlockData(a0)); }
    public static void setDisplayBlockOffset(org.bukkit.entity.Minecart e, int a0) { Shim.onEntity(e, () -> e.setDisplayBlockOffset(a0)); }
    public static void setDisplayHeight(org.bukkit.entity.Display e, float a0) { Shim.onEntity(e, () -> e.setDisplayHeight(a0)); }
    public static void setDisplayItem(org.bukkit.entity.SizedFireball e, org.bukkit.inventory.ItemStack a0) { Shim.onEntity(e, () -> e.setDisplayItem(a0)); }
    public static void setDisplayWidth(org.bukkit.entity.Display e, float a0) { Shim.onEntity(e, () -> e.setDisplayWidth(a0)); }
    public static void setDisturbanceLocation(org.bukkit.entity.Warden e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setDisturbanceLocation(a0)); }
    public static void setDomestication(org.bukkit.entity.AbstractHorse e, int a0) { Shim.onEntity(e, () -> e.setDomestication(a0)); }
    public static void setDrinkingPotion(org.bukkit.entity.Witch e, org.bukkit.inventory.ItemStack a0) { Shim.onEntity(e, () -> e.setDrinkingPotion(a0)); }
    public static void setDropItem(org.bukkit.entity.FallingBlock e, boolean a0) { Shim.onEntity(e, () -> e.setDropItem(a0)); }
    public static void setDuplicationCooldown(org.bukkit.entity.Allay e, long a0) { Shim.onEntity(e, () -> e.setDuplicationCooldown(a0)); }
    public static void setDuration(org.bukkit.entity.AreaEffectCloud e, int a0) { Shim.onEntity(e, () -> e.setDuration(a0)); }
    public static void setDurationOnUse(org.bukkit.entity.AreaEffectCloud e, int a0) { Shim.onEntity(e, () -> e.setDurationOnUse(a0)); }
    public static void setEating(org.bukkit.entity.Panda e, boolean a0) { Shim.onEntity(e, () -> e.setEating(a0)); }
    public static void setEatingGrass(org.bukkit.entity.AbstractHorse e, boolean a0) { Shim.onEntity(e, () -> e.setEatingGrass(a0)); }
    public static void setEatingHaystack(org.bukkit.entity.AbstractHorse e, boolean a0) { Shim.onEntity(e, () -> e.setEatingHaystack(a0)); }
    public static void setEatingTicks(org.bukkit.entity.Panda e, int a0) { Shim.onEntity(e, () -> e.setEatingTicks(a0)); }
    public static void setEggLayTime(org.bukkit.entity.Chicken e, int a0) { Shim.onEntity(e, () -> e.setEggLayTime(a0)); }
    public static void setEnchantmentSeed(org.bukkit.entity.HumanEntity e, int a0) { Shim.onEntity(e, () -> e.setEnchantmentSeed(a0)); }
    public static void setExhaustion(org.bukkit.entity.HumanEntity e, float a0) { Shim.onEntity(e, () -> e.setExhaustion(a0)); }
    public static void setExplosionPower(org.bukkit.entity.Ghast e, int a0) { Shim.onEntity(e, () -> e.setExplosionPower(a0)); }
    public static void setExplosionRadius(org.bukkit.entity.Creeper e, int a0) { Shim.onEntity(e, () -> e.setExplosionRadius(a0)); }
    public static void setFaceplanted(org.bukkit.entity.Fox e, boolean a0) { Shim.onEntity(e, () -> e.setFaceplanted(a0)); }
    public static boolean setFacingDirection(org.bukkit.entity.Hanging e, org.bukkit.block.BlockFace a0, boolean a1) { if (Shim.ownsEntity(e)) return e.setFacingDirection(a0, a1); ShimCore.ownScheduler().runAtEntity(e, t -> e.setFacingDirection(a0, a1)); return true; }
    public static void setFireworkMeta(org.bukkit.entity.Firework e, org.bukkit.inventory.meta.FireworkMeta a0) { Shim.onEntity(e, () -> e.setFireworkMeta(a0)); }
    public static void setFirstTrustedPlayer(org.bukkit.entity.Fox e, org.bukkit.entity.AnimalTamer a0) { Shim.onEntity(e, () -> e.setFirstTrustedPlayer(a0)); }
    public static void setFixed(org.bukkit.entity.ItemFrame e, boolean a0) { Shim.onEntity(e, () -> e.setFixed(a0)); }
    public static void setFlashCount(org.bukkit.entity.LightningStrike e, int a0) { Shim.onEntity(e, () -> e.setFlashCount(a0)); }
    public static void setFlashes(org.bukkit.entity.LightningStrike e, int a0) { Shim.onEntity(e, () -> e.setFlashes(a0)); }
    public static void setFlightSteps(org.bukkit.entity.ShulkerBullet e, int a0) { Shim.onEntity(e, () -> e.setFlightSteps(a0)); }
    public static void setFlower(org.bukkit.entity.Bee e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setFlower(a0)); }
    public static void setFlyingVelocityMod(org.bukkit.entity.Minecart e, org.bukkit.util.Vector a0) { Shim.onEntity(e, () -> e.setFlyingVelocityMod(a0)); }
    public static void setFoodLevel(org.bukkit.entity.HumanEntity e, int a0) { Shim.onEntity(e, () -> e.setFoodLevel(a0)); }
    public static void setFoxType(org.bukkit.entity.Fox e, org.bukkit.entity.Fox.Type a0) { Shim.onEntity(e, () -> e.setFoxType(a0)); }
    public static void setFreezeTicks(org.bukkit.entity.Entity e, int a0) { Shim.onEntity(e, () -> e.setFreezeTicks(a0)); }
    public static void setFuseTicks(org.bukkit.entity.TNTPrimed e, int a0) { Shim.onEntity(e, () -> e.setFuseTicks(a0)); }
    public static void setGliding(org.bukkit.entity.LivingEntity e, boolean a0) { Shim.onEntity(e, () -> e.setGliding(a0)); }
    public static void setGlint(org.bukkit.entity.Trident e, boolean a0) { Shim.onEntity(e, () -> e.setGlint(a0)); }
    public static void setGlowColorOverride(org.bukkit.entity.Display e, org.bukkit.Color a0) { Shim.onEntity(e, () -> e.setGlowColorOverride(a0)); }
    public static void setGlowingTicks(org.bukkit.entity.SpectralArrow e, int a0) { Shim.onEntity(e, () -> e.setGlowingTicks(a0)); }
    public static void setHasBeenShot(org.bukkit.entity.Projectile e, boolean a0) { Shim.onEntity(e, () -> e.setHasBeenShot(a0)); }
    public static void setHasBeenStaredAt(org.bukkit.entity.Enderman e, boolean a0) { Shim.onEntity(e, () -> e.setHasBeenStaredAt(a0)); }
    public static void setHasDealtDamage(org.bukkit.entity.Trident e, boolean a0) { Shim.onEntity(e, () -> e.setHasDealtDamage(a0)); }
    public static void setHasEgg(org.bukkit.entity.Turtle e, boolean a0) { Shim.onEntity(e, () -> e.setHasEgg(a0)); }
    public static void setHasFish(org.bukkit.entity.Dolphin e, boolean a0) { Shim.onEntity(e, () -> e.setHasFish(a0)); }
    public static void setHasLeftShooter(org.bukkit.entity.Projectile e, boolean a0) { Shim.onEntity(e, () -> e.setHasLeftShooter(a0)); }
    public static void setHasNectar(org.bukkit.entity.Bee e, boolean a0) { Shim.onEntity(e, () -> e.setHasNectar(a0)); }
    public static void setHasStung(org.bukkit.entity.Bee e, boolean a0) { Shim.onEntity(e, () -> e.setHasStung(a0)); }
    public static void setHeadPose(org.bukkit.entity.ArmorStand e, org.bukkit.util.EulerAngle a0) { Shim.onEntity(e, () -> e.setHeadPose(a0)); }
    public static void setHeadRotations(org.bukkit.entity.ArmorStand e, io.papermc.paper.math.Rotations a0) { Shim.onEntity(e, () -> e.setHeadRotations(a0)); }
    public static void setHeadUp(org.bukkit.entity.Cat e, boolean a0) { Shim.onEntity(e, () -> e.setHeadUp(a0)); }
    public static void setHealth(org.bukkit.entity.Item e, int a0) { Shim.onEntity(e, () -> e.setHealth(a0)); }
    public static void setHiddenGene(org.bukkit.entity.Panda e, org.bukkit.entity.Panda.Gene a0) { Shim.onEntity(e, () -> e.setHiddenGene(a0)); }
    public static void setHitSound(org.bukkit.entity.AbstractArrow e, org.bukkit.Sound a0) { Shim.onEntity(e, () -> e.setHitSound(a0)); }
    public static void setHive(org.bukkit.entity.Bee e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setHive(a0)); }
    public static void setHome(org.bukkit.entity.Turtle e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setHome(a0)); }
    public static void setHookedEntity(org.bukkit.entity.FishHook e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.setHookedEntity(a0)); }
    public static void setHurtDirection(org.bukkit.entity.HumanEntity e, float a0) { Shim.onEntity(e, () -> e.setHurtDirection(a0)); }
    public static void setHurtEntities(org.bukkit.entity.FallingBlock e, boolean a0) { Shim.onEntity(e, () -> e.setHurtEntities(a0)); }
    public static void setIgnited(org.bukkit.entity.Creeper e, boolean a0) { Shim.onEntity(e, () -> e.setIgnited(a0)); }
    public static void setImmuneToZombification(org.bukkit.entity.PiglinAbstract e, boolean a0) { Shim.onEntity(e, () -> e.setImmuneToZombification(a0)); }
    public static void setInteractionHeight(org.bukkit.entity.Interaction e, float a0) { Shim.onEntity(e, () -> e.setInteractionHeight(a0)); }
    public static void setInteractionWidth(org.bukkit.entity.Interaction e, float a0) { Shim.onEntity(e, () -> e.setInteractionWidth(a0)); }
    public static void setInterested(org.bukkit.entity.Fox e, boolean a0) { Shim.onEntity(e, () -> e.setInterested(a0)); }
    public static void setInterpolationDelay(org.bukkit.entity.Display e, int a0) { Shim.onEntity(e, () -> e.setInterpolationDelay(a0)); }
    public static void setInterpolationDuration(org.bukkit.entity.Display e, int a0) { Shim.onEntity(e, () -> e.setInterpolationDuration(a0)); }
    public static void setInvisible(org.bukkit.entity.Entity e, boolean a0) { Shim.onEntity(e, () -> e.setInvisible(a0)); }
    public static void setInvulnerabilityTicks(org.bukkit.entity.Wither e, int a0) { Shim.onEntity(e, () -> e.setInvulnerabilityTicks(a0)); }
    public static void setInvulnerable(org.bukkit.entity.Entity e, boolean a0) { Shim.onEntity(e, () -> e.setInvulnerable(a0)); }
    public static void setInvulnerableTicks(org.bukkit.entity.Wither e, int a0) { Shim.onEntity(e, () -> e.setInvulnerableTicks(a0)); }
    public static void setIsAbleToBeHunted(org.bukkit.entity.Hoglin e, boolean a0) { Shim.onEntity(e, () -> e.setIsAbleToBeHunted(a0)); }
    public static void setIsAbleToHunt(org.bukkit.entity.Piglin e, boolean a0) { Shim.onEntity(e, () -> e.setIsAbleToHunt(a0)); }
    public static void setIsChickenJockey(org.bukkit.entity.Chicken e, boolean a0) { Shim.onEntity(e, () -> e.setIsChickenJockey(a0)); }
    public static void setIsIncendiary(org.bukkit.entity.Explosive e, boolean a0) { Shim.onEntity(e, () -> e.setIsIncendiary(a0)); }
    public static void setItem(org.bukkit.entity.ThrownPotion e, org.bukkit.inventory.ItemStack a0) { Shim.onEntity(e, () -> e.setItem(a0)); }
    public static void setItem(org.bukkit.entity.ItemFrame e, org.bukkit.inventory.ItemStack a0, boolean a1) { Shim.onEntity(e, () -> e.setItem(a0, a1)); }
    public static void setItemDisplayTransform(org.bukkit.entity.ItemDisplay e, org.bukkit.entity.ItemDisplay.ItemDisplayTransform a0) { Shim.onEntity(e, () -> e.setItemDisplayTransform(a0)); }
    public static void setItemDropChance(org.bukkit.entity.ItemFrame e, float a0) { Shim.onEntity(e, () -> e.setItemDropChance(a0)); }
    public static void setItemInUseTicks(org.bukkit.entity.LivingEntity e, int a0) { Shim.onEntity(e, () -> e.setItemInUseTicks(a0)); }
    public static void setItemOnCursor(org.bukkit.entity.HumanEntity e, org.bukkit.inventory.ItemStack a0) { Shim.onEntity(e, () -> e.setItemOnCursor(a0)); }
    public static void setJohnny(org.bukkit.entity.Vindicator e, boolean a0) { Shim.onEntity(e, () -> e.setJohnny(a0)); }
    public static void setJumpStrength(org.bukkit.entity.AbstractHorse e, double a0) { Shim.onEntity(e, () -> e.setJumpStrength(a0)); }
    public static void setJumping(org.bukkit.entity.LivingEntity e, boolean a0) { Shim.onEntity(e, () -> e.setJumping(a0)); }
    public static void setKiller(org.bukkit.entity.LivingEntity e, org.bukkit.entity.Player a0) { Shim.onEntity(e, () -> e.setKiller(a0)); }
    public static boolean setLaser(org.bukkit.entity.Guardian e, boolean a0) { if (Shim.ownsEntity(e)) return e.setLaser(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.setLaser(a0)); return true; }
    public static void setLaserTicks(org.bukkit.entity.Guardian e, int a0) { Shim.onEntity(e, () -> e.setLaserTicks(a0)); }
    public static void setLastDamage(org.bukkit.entity.LivingEntity e, double a0) { Shim.onEntity(e, () -> e.setLastDamage(a0)); }
    public static void setLastDeathLocation(org.bukkit.entity.HumanEntity e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setLastDeathLocation(a0)); }
    public static void setLeaping(org.bukkit.entity.Fox e, boolean a0) { Shim.onEntity(e, () -> e.setLeaping(a0)); }
    public static void setLeftArmPose(org.bukkit.entity.ArmorStand e, org.bukkit.util.EulerAngle a0) { Shim.onEntity(e, () -> e.setLeftArmPose(a0)); }
    public static void setLeftArmRotations(org.bukkit.entity.ArmorStand e, io.papermc.paper.math.Rotations a0) { Shim.onEntity(e, () -> e.setLeftArmRotations(a0)); }
    public static void setLeftHanded(org.bukkit.entity.Mob e, boolean a0) { Shim.onEntity(e, () -> e.setLeftHanded(a0)); }
    public static void setLeftHorn(org.bukkit.entity.Goat e, boolean a0) { Shim.onEntity(e, () -> e.setLeftHorn(a0)); }
    public static void setLeftLegPose(org.bukkit.entity.ArmorStand e, org.bukkit.util.EulerAngle a0) { Shim.onEntity(e, () -> e.setLeftLegPose(a0)); }
    public static void setLeftLegRotations(org.bukkit.entity.ArmorStand e, io.papermc.paper.math.Rotations a0) { Shim.onEntity(e, () -> e.setLeftLegRotations(a0)); }
    public static boolean setLife(org.bukkit.entity.Firework e, int a0) { if (Shim.ownsEntity(e)) return e.setLife(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.setLife(a0)); return true; }
    public static void setLifeTicks(org.bukkit.entity.LightningStrike e, int a0) { Shim.onEntity(e, () -> e.setLifeTicks(a0)); }
    public static void setLifetimeTicks(org.bukkit.entity.AbstractArrow e, int a0) { Shim.onEntity(e, () -> e.setLifetimeTicks(a0)); }
    public static void setLimitedLifetime(org.bukkit.entity.Vex e, boolean a0) { Shim.onEntity(e, () -> e.setLimitedLifetime(a0)); }
    public static void setLimitedLifetimeTicks(org.bukkit.entity.Vex e, int a0) { Shim.onEntity(e, () -> e.setLimitedLifetimeTicks(a0)); }
    public static void setLineWidth(org.bukkit.entity.TextDisplay e, int a0) { Shim.onEntity(e, () -> e.setLineWidth(a0)); }
    public static void setLoveModeTicks(org.bukkit.entity.Animals e, int a0) { Shim.onEntity(e, () -> e.setLoveModeTicks(a0)); }
    public static void setLoyaltyLevel(org.bukkit.entity.Trident e, int a0) { Shim.onEntity(e, () -> e.setLoyaltyLevel(a0)); }
    public static void setLureAngle(org.bukkit.entity.FishHook e, float a0, float a1) { Shim.onEntity(e, () -> e.setLureAngle(a0, a1)); }
    public static void setLureTime(org.bukkit.entity.FishHook e, int a0, int a1) { Shim.onEntity(e, () -> e.setLureTime(a0, a1)); }
    public static void setLyingDown(org.bukkit.entity.Cat e, boolean a0) { Shim.onEntity(e, () -> e.setLyingDown(a0)); }
    public static void setMainGene(org.bukkit.entity.Panda e, org.bukkit.entity.Panda.Gene a0) { Shim.onEntity(e, () -> e.setMainGene(a0)); }
    public static void setMarker(org.bukkit.entity.ArmorStand e, boolean a0) { Shim.onEntity(e, () -> e.setMarker(a0)); }
    public static void setMaxDamage(org.bukkit.entity.FallingBlock e, int a0) { Shim.onEntity(e, () -> e.setMaxDamage(a0)); }
    public static void setMaxDomestication(org.bukkit.entity.AbstractHorse e, int a0) { Shim.onEntity(e, () -> e.setMaxDomestication(a0)); }
    public static void setMaxFuseTicks(org.bukkit.entity.Creeper e, int a0) { Shim.onEntity(e, () -> e.setMaxFuseTicks(a0)); }
    public static void setMaxHealth(org.bukkit.entity.Damageable e, double a0) { Shim.onEntity(e, () -> e.setMaxHealth(a0)); }
    public static boolean setMaxLife(org.bukkit.entity.Firework e, int a0) { if (Shim.ownsEntity(e)) return e.setMaxLife(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.setMaxLife(a0)); return true; }
    public static void setMaxLureAngle(org.bukkit.entity.FishHook e, float a0) { Shim.onEntity(e, () -> e.setMaxLureAngle(a0)); }
    public static void setMaxLureTime(org.bukkit.entity.FishHook e, int a0) { Shim.onEntity(e, () -> e.setMaxLureTime(a0)); }
    public static void setMaxSpeed(org.bukkit.entity.Boat e, double a0) { Shim.onEntity(e, () -> e.setMaxSpeed(a0)); }
    public static void setMaxWaitTime(org.bukkit.entity.FishHook e, int a0) { Shim.onEntity(e, () -> e.setMaxWaitTime(a0)); }
    public static void setMaximumAir(org.bukkit.entity.LivingEntity e, int a0) { Shim.onEntity(e, () -> e.setMaximumAir(a0)); }
    public static void setMaximumNoDamageTicks(org.bukkit.entity.LivingEntity e, int a0) { Shim.onEntity(e, () -> e.setMaximumNoDamageTicks(a0)); }
    public static void setMemory(org.bukkit.entity.LivingEntity e, org.bukkit.entity.memory.MemoryKey a0, java.lang.Object a1) { Shim.onEntity(e, () -> e.setMemory(a0, a1)); }
    public static void setMinLureAngle(org.bukkit.entity.FishHook e, float a0) { Shim.onEntity(e, () -> e.setMinLureAngle(a0)); }
    public static void setMinLureTime(org.bukkit.entity.FishHook e, int a0) { Shim.onEntity(e, () -> e.setMinLureTime(a0)); }
    public static void setMinWaitTime(org.bukkit.entity.FishHook e, int a0) { Shim.onEntity(e, () -> e.setMinWaitTime(a0)); }
    public static void setMoistness(org.bukkit.entity.Dolphin e, int a0) { Shim.onEntity(e, () -> e.setMoistness(a0)); }
    public static void setMoreCarrotTicks(org.bukkit.entity.Rabbit e, int a0) { Shim.onEntity(e, () -> e.setMoreCarrotTicks(a0)); }
    public static void setNoActionTicks(org.bukkit.entity.LivingEntity e, int a0) { Shim.onEntity(e, () -> e.setNoActionTicks(a0)); }
    public static void setNoDamageTicks(org.bukkit.entity.LivingEntity e, int a0) { Shim.onEntity(e, () -> e.setNoDamageTicks(a0)); }
    public static void setNoPhysics(org.bukkit.entity.Entity e, boolean a0) { Shim.onEntity(e, () -> e.setNoPhysics(a0)); }
    public static void setOccupiedDeceleration(org.bukkit.entity.Boat e, double a0) { Shim.onEntity(e, () -> e.setOccupiedDeceleration(a0)); }
    public static void setOnBack(org.bukkit.entity.Panda e, boolean a0) { Shim.onEntity(e, () -> e.setOnBack(a0)); }
    public static void setOwner(org.bukkit.entity.Item e, java.util.UUID a0) { Shim.onEntity(e, () -> e.setOwner(a0)); }
    public static void setOwner(org.bukkit.entity.Tameable e, org.bukkit.entity.AnimalTamer a0) { Shim.onEntity(e, () -> e.setOwner(a0)); }
    public static void setOwner(org.bukkit.entity.EvokerFangs e, org.bukkit.entity.LivingEntity a0) { Shim.onEntity(e, () -> e.setOwner(a0)); }
    public static void setOwnerUniqueId(org.bukkit.entity.AreaEffectCloud e, java.util.UUID a0) { Shim.onEntity(e, () -> e.setOwnerUniqueId(a0)); }
    public static void setParticle(org.bukkit.entity.AreaEffectCloud e, org.bukkit.Particle a0, java.lang.Object a1) { Shim.onEntity(e, () -> e.setParticle(a0, a1)); }
    public static boolean setPassenger(org.bukkit.entity.Entity e, org.bukkit.entity.Entity a0) { if (Shim.ownsEntity(e)) return e.setPassenger(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.setPassenger(a0)); return true; }
    public static void setPatrolLeader(org.bukkit.entity.Raider e, boolean a0) { Shim.onEntity(e, () -> e.setPatrolLeader(a0)); }
    public static void setPatrolTarget(org.bukkit.entity.Raider e, org.bukkit.block.Block a0) { Shim.onEntity(e, () -> e.setPatrolTarget(a0)); }
    public static void setPattern(org.bukkit.entity.TropicalFish e, org.bukkit.entity.TropicalFish.Pattern a0) { Shim.onEntity(e, () -> e.setPattern(a0)); }
    public static void setPatternColor(org.bukkit.entity.TropicalFish e, org.bukkit.DyeColor a0) { Shim.onEntity(e, () -> e.setPatternColor(a0)); }
    public static void setPeek(org.bukkit.entity.Shulker e, float a0) { Shim.onEntity(e, () -> e.setPeek(a0)); }
    public static void setPhase(org.bukkit.entity.EnderDragon e, org.bukkit.entity.EnderDragon.Phase a0) { Shim.onEntity(e, () -> e.setPhase(a0)); }
    public static void setPickupDelay(org.bukkit.entity.Item e, int a0) { Shim.onEntity(e, () -> e.setPickupDelay(a0)); }
    public static void setPickupStatus(org.bukkit.entity.AbstractArrow e, org.bukkit.entity.AbstractArrow.PickupStatus a0) { Shim.onEntity(e, () -> e.setPickupStatus(a0)); }
    public static void setPierceLevel(org.bukkit.entity.AbstractArrow e, int a0) { Shim.onEntity(e, () -> e.setPierceLevel(a0)); }
    public static void setPlayerCreated(org.bukkit.entity.IronGolem e, boolean a0) { Shim.onEntity(e, () -> e.setPlayerCreated(a0)); }
    public static void setPlayingDead(org.bukkit.entity.Axolotl e, boolean a0) { Shim.onEntity(e, () -> e.setPlayingDead(a0)); }
    public static void setPodium(org.bukkit.entity.EnderDragon e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setPodium(a0)); }
    public static void setPortalCooldown(org.bukkit.entity.Entity e, int a0) { Shim.onEntity(e, () -> e.setPortalCooldown(a0)); }
    public static void setPotionMeta(org.bukkit.entity.ThrownPotion e, org.bukkit.inventory.meta.PotionMeta a0) { Shim.onEntity(e, () -> e.setPotionMeta(a0)); }
    public static void setPotionUseTimeLeft(org.bukkit.entity.Witch e, int a0) { Shim.onEntity(e, () -> e.setPotionUseTimeLeft(a0)); }
    public static void setPowered(org.bukkit.entity.Creeper e, boolean a0) { Shim.onEntity(e, () -> e.setPowered(a0)); }
    public static void setProfession(org.bukkit.entity.Villager e, org.bukkit.entity.Villager.Profession a0) { Shim.onEntity(e, () -> e.setProfession(a0)); }
    public static void setPuffState(org.bukkit.entity.PufferFish e, int a0) { Shim.onEntity(e, () -> e.setPuffState(a0)); }
    public static void setRabbitType(org.bukkit.entity.Rabbit e, org.bukkit.entity.Rabbit.Type a0) { Shim.onEntity(e, () -> e.setRabbitType(a0)); }
    public static void setRadius(org.bukkit.entity.AreaEffectCloud e, float a0) { Shim.onEntity(e, () -> e.setRadius(a0)); }
    public static void setRadiusOnUse(org.bukkit.entity.AreaEffectCloud e, float a0) { Shim.onEntity(e, () -> e.setRadiusOnUse(a0)); }
    public static void setRadiusPerTick(org.bukkit.entity.AreaEffectCloud e, float a0) { Shim.onEntity(e, () -> e.setRadiusPerTick(a0)); }
    public static void setRaid(org.bukkit.entity.Raider e, org.bukkit.Raid a0) { Shim.onEntity(e, () -> e.setRaid(a0)); }
    public static void setRainInfluenced(org.bukkit.entity.FishHook e, boolean a0) { Shim.onEntity(e, () -> e.setRainInfluenced(a0)); }
    public static void setReapplicationDelay(org.bukkit.entity.AreaEffectCloud e, int a0) { Shim.onEntity(e, () -> e.setReapplicationDelay(a0)); }
    public static void setRearing(org.bukkit.entity.AbstractHorse e, boolean a0) { Shim.onEntity(e, () -> e.setRearing(a0)); }
    public static void setRemainingAir(org.bukkit.entity.LivingEntity e, int a0) { Shim.onEntity(e, () -> e.setRemainingAir(a0)); }
    public static void setReputation(org.bukkit.entity.Villager e, java.util.UUID a0, com.destroystokyo.paper.entity.villager.Reputation a1) { Shim.onEntity(e, () -> e.setReputation(a0, a1)); }
    public static void setResponsive(org.bukkit.entity.Interaction e, boolean a0) { Shim.onEntity(e, () -> e.setResponsive(a0)); }
    public static void setRestocksToday(org.bukkit.entity.Villager e, int a0) { Shim.onEntity(e, () -> e.setRestocksToday(a0)); }
    public static void setRightArmPose(org.bukkit.entity.ArmorStand e, org.bukkit.util.EulerAngle a0) { Shim.onEntity(e, () -> e.setRightArmPose(a0)); }
    public static void setRightArmRotations(org.bukkit.entity.ArmorStand e, io.papermc.paper.math.Rotations a0) { Shim.onEntity(e, () -> e.setRightArmRotations(a0)); }
    public static void setRightHorn(org.bukkit.entity.Goat e, boolean a0) { Shim.onEntity(e, () -> e.setRightHorn(a0)); }
    public static void setRightLegPose(org.bukkit.entity.ArmorStand e, org.bukkit.util.EulerAngle a0) { Shim.onEntity(e, () -> e.setRightLegPose(a0)); }
    public static void setRightLegRotations(org.bukkit.entity.ArmorStand e, io.papermc.paper.math.Rotations a0) { Shim.onEntity(e, () -> e.setRightLegRotations(a0)); }
    public static void setRiptiding(org.bukkit.entity.LivingEntity e, boolean a0) { Shim.onEntity(e, () -> e.setRiptiding(a0)); }
    public static void setRoarTicks(org.bukkit.entity.Ravager e, int a0) { Shim.onEntity(e, () -> e.setRoarTicks(a0)); }
    public static void setRolling(org.bukkit.entity.Panda e, boolean a0) { Shim.onEntity(e, () -> e.setRolling(a0)); }
    public static void setRollingOverride(org.bukkit.entity.Bee e, net.kyori.adventure.util.TriState a0) { Shim.onEntity(e, () -> e.setRollingOverride(a0)); }
    public static void setRotation(org.bukkit.entity.Entity e, float a0, float a1) { Shim.onEntity(e, () -> e.setRotation(a0, a1)); }
    public static void setRotation(org.bukkit.entity.ItemFrame e, org.bukkit.Rotation a0) { Shim.onEntity(e, () -> e.setRotation(a0)); }
    public static void setSaddle(org.bukkit.entity.Steerable e, boolean a0) { Shim.onEntity(e, () -> e.setSaddle(a0)); }
    public static void setSaturatedRegenRate(org.bukkit.entity.HumanEntity e, int a0) { Shim.onEntity(e, () -> e.setSaturatedRegenRate(a0)); }
    public static void setSaturation(org.bukkit.entity.HumanEntity e, float a0) { Shim.onEntity(e, () -> e.setSaturation(a0)); }
    public static void setScreaming(org.bukkit.entity.Enderman e, boolean a0) { Shim.onEntity(e, () -> e.setScreaming(a0)); }
    public static void setSecondTrustedPlayer(org.bukkit.entity.Fox e, org.bukkit.entity.AnimalTamer a0) { Shim.onEntity(e, () -> e.setSecondTrustedPlayer(a0)); }
    public static void setShadowRadius(org.bukkit.entity.Display e, float a0) { Shim.onEntity(e, () -> e.setShadowRadius(a0)); }
    public static void setShadowStrength(org.bukkit.entity.Display e, float a0) { Shim.onEntity(e, () -> e.setShadowStrength(a0)); }
    public static void setSheared(org.bukkit.entity.Bogged e, boolean a0) { Shim.onEntity(e, () -> e.setSheared(a0)); }
    public static void setShivering(org.bukkit.entity.Strider e, boolean a0) { Shim.onEntity(e, () -> e.setShivering(a0)); }
    public static void setShooter(org.bukkit.entity.Projectile e, org.bukkit.projectiles.ProjectileSource a0) { Shim.onEntity(e, () -> e.setShooter(a0)); }
    public static void setShooter(org.bukkit.entity.AbstractArrow e, org.bukkit.projectiles.ProjectileSource a0, boolean a1) { Shim.onEntity(e, () -> e.setShooter(a0, a1)); }
    public static void setShotAtAngle(org.bukkit.entity.Firework e, boolean a0) { Shim.onEntity(e, () -> e.setShotAtAngle(a0)); }
    public static void setShouldBurnInDay(org.bukkit.entity.Zombie e, boolean a0) { Shim.onEntity(e, () -> e.setShouldBurnInDay(a0)); }
    public static void setShoulderEntityLeft(org.bukkit.entity.HumanEntity e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.setShoulderEntityLeft(a0)); }
    public static void setShoulderEntityRight(org.bukkit.entity.HumanEntity e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.setShoulderEntityRight(a0)); }
    public static void setShowingBottom(org.bukkit.entity.EnderCrystal e, boolean a0) { Shim.onEntity(e, () -> e.setShowingBottom(a0)); }
    public static void setSitting(org.bukkit.entity.Sittable e, boolean a0) { Shim.onEntity(e, () -> e.setSitting(a0)); }
    public static void setSize(org.bukkit.entity.Slime e, int a0) { Shim.onEntity(e, () -> e.setSize(a0)); }
    public static void setSkyInfluenced(org.bukkit.entity.FishHook e, boolean a0) { Shim.onEntity(e, () -> e.setSkyInfluenced(a0)); }
    public static void setSleeping(org.bukkit.entity.Fox e, boolean a0) { Shim.onEntity(e, () -> e.setSleeping(a0)); }
    public static void setSlowWhenEmpty(org.bukkit.entity.Minecart e, boolean a0) { Shim.onEntity(e, () -> e.setSlowWhenEmpty(a0)); }
    public static void setSmall(org.bukkit.entity.ArmorStand e, boolean a0) { Shim.onEntity(e, () -> e.setSmall(a0)); }
    public static void setSneaking(org.bukkit.entity.Entity e, boolean a0) { Shim.onEntity(e, () -> e.setSneaking(a0)); }
    public static void setSneezeTicks(org.bukkit.entity.Panda e, int a0) { Shim.onEntity(e, () -> e.setSneezeTicks(a0)); }
    public static void setSneezing(org.bukkit.entity.Panda e, boolean a0) { Shim.onEntity(e, () -> e.setSneezing(a0)); }
    public static void setSource(org.bukkit.entity.TNTPrimed e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.setSource(a0)); }
    public static void setSource(org.bukkit.entity.AreaEffectCloud e, org.bukkit.projectiles.ProjectileSource a0) { Shim.onEntity(e, () -> e.setSource(a0)); }
    public static void setSpawnItemAfterTicks(org.bukkit.entity.OminousItemSpawner e, long a0) { Shim.onEntity(e, () -> e.setSpawnItemAfterTicks(a0)); }
    public static void setSpectatorTarget(org.bukkit.entity.Player e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.setSpectatorTarget(a0)); }
    public static void setSpell(org.bukkit.entity.Spellcaster e, org.bukkit.entity.Spellcaster.Spell a0) { Shim.onEntity(e, () -> e.setSpell(a0)); }
    public static void setStanding(org.bukkit.entity.PolarBear e, boolean a0) { Shim.onEntity(e, () -> e.setStanding(a0)); }
    public static void setStarvationRate(org.bukkit.entity.HumanEntity e, int a0) { Shim.onEntity(e, () -> e.setStarvationRate(a0)); }
    public static void setState(org.bukkit.entity.Sniffer e, org.bukkit.entity.Sniffer.State a0) { Shim.onEntity(e, () -> e.setState(a0)); }
    public static void setStewEffects(org.bukkit.entity.MushroomCow e, java.util.List a0) { Shim.onEntity(e, () -> e.setStewEffects(a0)); }
    public static void setStrength(org.bukkit.entity.Llama e, int a0) { Shim.onEntity(e, () -> e.setStrength(a0)); }
    public static void setStunnedTicks(org.bukkit.entity.Ravager e, int a0) { Shim.onEntity(e, () -> e.setStunnedTicks(a0)); }
    public static void setStyle(org.bukkit.entity.Horse e, org.bukkit.entity.Horse.Style a0) { Shim.onEntity(e, () -> e.setStyle(a0)); }
    public static void setSummoner(org.bukkit.entity.Vex e, org.bukkit.entity.Mob a0) { Shim.onEntity(e, () -> e.setSummoner(a0)); }
    public static void setSwimming(org.bukkit.entity.LivingEntity e, boolean a0) { Shim.onEntity(e, () -> e.setSwimming(a0)); }
    public static void setTamed(org.bukkit.entity.Tameable e, boolean a0) { Shim.onEntity(e, () -> e.setTamed(a0)); }
    public static void setTarget(org.bukkit.entity.ShulkerBullet e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.setTarget(a0)); }
    public static void setTarget(org.bukkit.entity.Mob e, org.bukkit.entity.LivingEntity a0) { Shim.onEntity(e, () -> e.setTarget(a0)); }
    public static void setTarget(org.bukkit.entity.Wither e, org.bukkit.entity.Wither.Head a0, org.bukkit.entity.LivingEntity a1) { Shim.onEntity(e, () -> e.setTarget(a0, a1)); }
    public static void setTargetDelta(org.bukkit.entity.ShulkerBullet e, org.bukkit.util.Vector a0) { Shim.onEntity(e, () -> e.setTargetDelta(a0)); }
    public static void setTargetLocation(org.bukkit.entity.Bat e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setTargetLocation(a0)); }
    public static void setTargetLocation(org.bukkit.entity.EnderSignal e, org.bukkit.Location a0, boolean a1) { Shim.onEntity(e, () -> e.setTargetLocation(a0, a1)); }
    public static void setTeleportDuration(org.bukkit.entity.Display e, int a0) { Shim.onEntity(e, () -> e.setTeleportDuration(a0)); }
    public static void setText(org.bukkit.entity.TextDisplay e, java.lang.String a0) { Shim.onEntity(e, () -> e.setText(a0)); }
    public static void setTextOpacity(org.bukkit.entity.TextDisplay e, byte a0) { Shim.onEntity(e, () -> e.setTextOpacity(a0)); }
    public static void setThrower(org.bukkit.entity.Item e, java.util.UUID a0) { Shim.onEntity(e, () -> e.setThrower(a0)); }
    public static void setTicksFlown(org.bukkit.entity.Firework e, int a0) { Shim.onEntity(e, () -> e.setTicksFlown(a0)); }
    public static void setTicksLived(org.bukkit.entity.Entity e, int a0) { Shim.onEntity(e, () -> e.setTicksLived(a0)); }
    public static void setTicksOutsideRaid(org.bukkit.entity.Raider e, int a0) { Shim.onEntity(e, () -> e.setTicksOutsideRaid(a0)); }
    public static void setTicksSincePollination(org.bukkit.entity.Bee e, int a0) { Shim.onEntity(e, () -> e.setTicksSincePollination(a0)); }
    public static void setTicksToDetonate(org.bukkit.entity.Firework e, int a0) { Shim.onEntity(e, () -> e.setTicksToDetonate(a0)); }
    public static void setTimeUntilBite(org.bukkit.entity.FishHook e, int a0) { Shim.onEntity(e, () -> e.setTimeUntilBite(a0)); }
    public static void setTongueTarget(org.bukkit.entity.Frog e, org.bukkit.entity.Entity a0) { Shim.onEntity(e, () -> e.setTongueTarget(a0)); }
    public static void setTransformation(org.bukkit.entity.Display e, org.bukkit.util.Transformation a0) { Shim.onEntity(e, () -> e.setTransformation(a0)); }
    public static void setTransformationMatrix(org.bukkit.entity.Display e, org.joml.Matrix4f a0) { Shim.onEntity(e, () -> e.setTransformationMatrix(a0)); }
    public static void setTrapTime(org.bukkit.entity.SkeletonHorse e, int a0) { Shim.onEntity(e, () -> e.setTrapTime(a0)); }
    public static void setTrapped(org.bukkit.entity.SkeletonHorse e, boolean a0) { Shim.onEntity(e, () -> e.setTrapped(a0)); }
    public static void setTreasureLocation(org.bukkit.entity.Dolphin e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setTreasureLocation(a0)); }
    public static void setTrusting(org.bukkit.entity.Ocelot e, boolean a0) { Shim.onEntity(e, () -> e.setTrusting(a0)); }
    public static void setUnhappyTicks(org.bukkit.entity.Panda e, int a0) { Shim.onEntity(e, () -> e.setUnhappyTicks(a0)); }
    public static void setUnlimitedLifetime(org.bukkit.entity.Item e, boolean a0) { Shim.onEntity(e, () -> e.setUnlimitedLifetime(a0)); }
    public static void setUnoccupiedDeceleration(org.bukkit.entity.Boat e, double a0) { Shim.onEntity(e, () -> e.setUnoccupiedDeceleration(a0)); }
    public static void setUnsaturatedRegenRate(org.bukkit.entity.HumanEntity e, int a0) { Shim.onEntity(e, () -> e.setUnsaturatedRegenRate(a0)); }
    public static void setVariant(org.bukkit.entity.Axolotl e, org.bukkit.entity.Axolotl.Variant a0) { Shim.onEntity(e, () -> e.setVariant(a0)); }
    public static void setVariant(org.bukkit.entity.Frog e, org.bukkit.entity.Frog.Variant a0) { Shim.onEntity(e, () -> e.setVariant(a0)); }
    public static void setVariant(org.bukkit.entity.MushroomCow e, org.bukkit.entity.MushroomCow.Variant a0) { Shim.onEntity(e, () -> e.setVariant(a0)); }
    public static void setVariant(org.bukkit.entity.Parrot e, org.bukkit.entity.Parrot.Variant a0) { Shim.onEntity(e, () -> e.setVariant(a0)); }
    public static void setVariant(org.bukkit.entity.Salmon e, org.bukkit.entity.Salmon.Variant a0) { Shim.onEntity(e, () -> e.setVariant(a0)); }
    public static void setVariant(org.bukkit.entity.Wolf e, org.bukkit.entity.Wolf.Variant a0) { Shim.onEntity(e, () -> e.setVariant(a0)); }
    public static void setViewRange(org.bukkit.entity.Display e, float a0) { Shim.onEntity(e, () -> e.setViewRange(a0)); }
    public static void setVillagerExperience(org.bukkit.entity.Villager e, int a0) { Shim.onEntity(e, () -> e.setVillagerExperience(a0)); }
    public static void setVillagerLevel(org.bukkit.entity.Villager e, int a0) { Shim.onEntity(e, () -> e.setVillagerLevel(a0)); }
    public static void setVillagerProfession(org.bukkit.entity.ZombieVillager e, org.bukkit.entity.Villager.Profession a0) { Shim.onEntity(e, () -> e.setVillagerProfession(a0)); }
    public static void setVillagerType(org.bukkit.entity.Villager e, org.bukkit.entity.Villager.Type a0) { Shim.onEntity(e, () -> e.setVillagerType(a0)); }
    public static void setVisible(org.bukkit.entity.ItemFrame e, boolean a0) { Shim.onEntity(e, () -> e.setVisible(a0)); }
    public static void setVisibleByDefault(org.bukkit.entity.Entity e, boolean a0) { Shim.onEntity(e, () -> e.setVisibleByDefault(a0)); }
    public static void setWaitTime(org.bukkit.entity.FishHook e, int a0) { Shim.onEntity(e, () -> e.setWaitTime(a0)); }
    public static void setWaitTime(org.bukkit.entity.FishHook e, int a0, int a1) { Shim.onEntity(e, () -> e.setWaitTime(a0, a1)); }
    public static void setWander(org.bukkit.entity.Slime e, boolean a0) { Shim.onEntity(e, () -> e.setWander(a0)); }
    public static void setWanderingTowards(org.bukkit.entity.WanderingTrader e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.setWanderingTowards(a0)); }
    public static void setWave(org.bukkit.entity.Raider e, int a0) { Shim.onEntity(e, () -> e.setWave(a0)); }
    public static void setWeapon(org.bukkit.entity.AbstractArrow e, org.bukkit.inventory.ItemStack a0) { Shim.onEntity(e, () -> e.setWeapon(a0)); }
    public static void setWillAge(org.bukkit.entity.Item e, boolean a0) { Shim.onEntity(e, () -> e.setWillAge(a0)); }
    public static void setWololoTarget(org.bukkit.entity.Evoker e, org.bukkit.entity.Sheep a0) { Shim.onEntity(e, () -> e.setWololoTarget(a0)); }
    public static void setWorkOnLand(org.bukkit.entity.Boat e, boolean a0) { Shim.onEntity(e, () -> e.setWorkOnLand(a0)); }
    public static void setYield(org.bukkit.entity.Explosive e, float a0) { Shim.onEntity(e, () -> e.setYield(a0)); }
    public static void shakeHead(org.bukkit.entity.Villager e) { Shim.onEntity(e, () -> e.shakeHead()); }
    public static void shouldAutoExpire(org.bukkit.entity.FallingBlock e, boolean a0) { Shim.onEntity(e, () -> e.shouldAutoExpire(a0)); }
    public static boolean shouldBurnInDay(org.bukkit.entity.Zombie e) { if (Shim.ownsEntity(e)) return e.shouldBurnInDay(); ShimCore.ownScheduler().runAtEntity(e, t -> e.shouldBurnInDay()); return true; }
    public static boolean sleep(org.bukkit.entity.Villager e, org.bukkit.Location a0) { if (Shim.ownsEntity(e)) return e.sleep(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.sleep(a0)); return true; }
    public static boolean sleep(org.bukkit.entity.HumanEntity e, org.bukkit.Location a0, boolean a1) { if (Shim.ownsEntity(e)) return e.sleep(a0, a1); ShimCore.ownScheduler().runAtEntity(e, t -> e.sleep(a0, a1)); return true; }
    public static void splash(org.bukkit.entity.ThrownPotion e) { Shim.onEntity(e, () -> e.splash()); }
    public static void startDancing(org.bukkit.entity.Allay e) { Shim.onEntity(e, () -> e.startDancing()); }
    public static void startDancing(org.bukkit.entity.Allay e, org.bukkit.Location a0) { Shim.onEntity(e, () -> e.startDancing(a0)); }
    public static void startDrowning(org.bukkit.entity.Zombie e, int a0) { Shim.onEntity(e, () -> e.startDrowning(a0)); }
    public static void startRiptideAttack(org.bukkit.entity.HumanEntity e, int a0, float a1, org.bukkit.inventory.ItemStack a2) { Shim.onEntity(e, () -> e.startRiptideAttack(a0, a1, a2)); }
    public static void startUsingItem(org.bukkit.entity.LivingEntity e, org.bukkit.inventory.EquipmentSlot a0) { Shim.onEntity(e, () -> e.startUsingItem(a0)); }
    public static void stopDancing(org.bukkit.entity.Allay e) { Shim.onEntity(e, () -> e.stopDancing()); }
    public static void stopDrowning(org.bukkit.entity.Zombie e) { Shim.onEntity(e, () -> e.stopDrowning()); }
    public static void swingMainHand(org.bukkit.entity.LivingEntity e) { Shim.onEntity(e, () -> e.swingMainHand()); }
    public static void swingOffHand(org.bukkit.entity.LivingEntity e) { Shim.onEntity(e, () -> e.swingOffHand()); }
    public static boolean teleport(org.bukkit.entity.Enderman e) { if (Shim.ownsEntity(e)) return e.teleport(); ShimCore.ownScheduler().runAtEntity(e, t -> e.teleport()); return true; }
    public static boolean teleportRandomly(org.bukkit.entity.Enderman e) { if (Shim.ownsEntity(e)) return e.teleportRandomly(); ShimCore.ownScheduler().runAtEntity(e, t -> e.teleportRandomly()); return true; }
    public static boolean teleportTowards(org.bukkit.entity.Enderman e, org.bukkit.entity.Entity a0) { if (Shim.ownsEntity(e)) return e.teleportTowards(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.teleportTowards(a0)); return true; }
    public static void text(org.bukkit.entity.TextDisplay e, net.kyori.adventure.text.Component a0) { Shim.onEntity(e, () -> e.text(a0)); }
    public static void wakeup(org.bukkit.entity.Villager e) { Shim.onEntity(e, () -> e.wakeup()); }
    public static void wakeup(org.bukkit.entity.HumanEntity e, boolean a0) { Shim.onEntity(e, () -> e.wakeup(a0)); }
    public static boolean willAge(org.bukkit.entity.Item e) { if (Shim.ownsEntity(e)) return e.willAge(); ShimCore.ownScheduler().runAtEntity(e, t -> e.willAge()); return true; }
    public static boolean wouldCollideUsing(org.bukkit.entity.Entity e, org.bukkit.util.BoundingBox a0) { if (Shim.ownsEntity(e)) return e.wouldCollideUsing(a0); ShimCore.ownScheduler().runAtEntity(e, t -> e.wouldCollideUsing(a0)); return true; }
    public static void explode(org.bukkit.entity.minecart.ExplosiveMinecart e) { Shim.onEntity(e, () -> e.explode()); }
    public static void explode(org.bukkit.entity.minecart.ExplosiveMinecart e, double a0) { Shim.onEntity(e, () -> e.explode(a0)); }
    public static void ignite(org.bukkit.entity.minecart.ExplosiveMinecart e) { Shim.onEntity(e, () -> e.ignite()); }
    public static boolean isEnabled(org.bukkit.entity.minecart.HopperMinecart e) { if (Shim.ownsEntity(e)) return e.isEnabled(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isEnabled()); return true; }
    public static boolean isIgnited(org.bukkit.entity.minecart.ExplosiveMinecart e) { if (Shim.ownsEntity(e)) return e.isIgnited(); ShimCore.ownScheduler().runAtEntity(e, t -> e.isIgnited()); return true; }
    public static void setCommand(org.bukkit.entity.minecart.CommandMinecart e, java.lang.String a0) { Shim.onEntity(e, () -> e.setCommand(a0)); }
    public static void setEnabled(org.bukkit.entity.minecart.HopperMinecart e, boolean a0) { Shim.onEntity(e, () -> e.setEnabled(a0)); }
    public static void setExplosionSpeedFactor(org.bukkit.entity.minecart.ExplosiveMinecart e, float a0) { Shim.onEntity(e, () -> e.setExplosionSpeedFactor(a0)); }
    public static void setFuel(org.bukkit.entity.minecart.PoweredMinecart e, int a0) { Shim.onEntity(e, () -> e.setFuel(a0)); }
    public static void setFuseTicks(org.bukkit.entity.minecart.ExplosiveMinecart e, int a0) { Shim.onEntity(e, () -> e.setFuseTicks(a0)); }
    public static void setName(org.bukkit.entity.minecart.CommandMinecart e, java.lang.String a0) { Shim.onEntity(e, () -> e.setName(a0)); }
    public static void setPushX(org.bukkit.entity.minecart.PoweredMinecart e, double a0) { Shim.onEntity(e, () -> e.setPushX(a0)); }
    public static void setPushZ(org.bukkit.entity.minecart.PoweredMinecart e, double a0) { Shim.onEntity(e, () -> e.setPushZ(a0)); }

    private ShimGenerated() {
    }
}
