import { spawn } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { FOLIA_DIR } from "../env.js";

const WORK_DIR = path.join(FOLIA_DIR, "work");

// A non-default, high port so the harness never collides with a real server
// the user may have running (which owns 25565).
const HARNESS_PORT = 25599;

const SERVER_PROPERTIES = [
  "level-type=flat",
  'generator-settings={"layers":[{"block":"minecraft:bedrock","height":1},{"block":"minecraft:dirt","height":2},{"block":"minecraft:grass_block","height":1}],"biome":"minecraft:plains"}',
  "view-distance=4",
  "simulation-distance=4",
  "online-mode=false",
  "spawn-protection=0",
  "max-players=1",
  `server-port=${HARNESS_PORT}`,
  `query.port=${HARNESS_PORT}`,
  "motd=Turnleaf harness",
  "",
].join("\n");

export interface BootOptions {
  /** Log lines that must appear for the boot to count as passed. */
  expectMarkers?: string[];
  /** Substrings (package/plugin names) that scope errors to the plugin under test. */
  pluginScopes?: string[];
  /** Seconds to wait for the server to reach "Done". Default 420. */
  timeoutSeconds?: number;
  /** Seconds to keep the server running after "Done" so tasks can tick. Default 8. */
  settleSeconds?: number;
}

export interface BootResult {
  ok: boolean;
  reachedDone: boolean;
  enabledPlugins: string[];
  missingPlugins: string[];
  markersFound: string[];
  markersMissing: string[];
  /** Plugin-scoped problems — these fail the verdict. */
  fatalIssues: string[];
  /** Unrelated server noise — reported, never fails the verdict. */
  noise: string[];
  exitCode: number | null;
  bootSeconds: number;
  logFile: string;
}

export function findServerJar(): string {
  const jars = fs.existsSync(FOLIA_DIR)
    ? fs.readdirSync(FOLIA_DIR).filter((f) => f.endsWith(".jar"))
    : [];
  if (jars.length === 0) throw new Error(`No Folia server jar found in ${FOLIA_DIR}`);
  return path.join(FOLIA_DIR, jars[0]);
}

function prepareWorkDir(pluginJars: string[]): void {
  fs.mkdirSync(WORK_DIR, { recursive: true });
  fs.writeFileSync(path.join(WORK_DIR, "eula.txt"), "eula=true\n");
  // Always (re)write so the non-default port is guaranteed even if an older
  // server.properties (without server-port) was generated by a prior boot.
  fs.writeFileSync(path.join(WORK_DIR, "server.properties"), SERVER_PROPERTIES);

  const pluginsDir = path.join(WORK_DIR, "plugins");
  // Fully fresh plugins dir each run (jars AND generated plugin data), so a
  // stale/locked data file from a prior boot can't cause a flaky failure. The
  // generated world is kept for fast boots.
  fs.rmSync(pluginsDir, { recursive: true, force: true });
  fs.mkdirSync(pluginsDir, { recursive: true });
  for (const jar of pluginJars) {
    fs.copyFileSync(jar, path.join(pluginsDir, path.basename(jar)));
  }
}

/** Lines that indicate a plugin problem regardless of which package they mention. */
const ALWAYS_FATAL_PATTERNS = [
  /Error occurred while enabling/,
  /Could not load plugin/,
  /not marked as supporting Folia/i,
  /UnknownDependency/,
  /failed main thread check/,
  /UnsupportedOperationException/,
];

/** Generic trouble indicators — fatal only when the line mentions the plugin under test. */
const GENERIC_ISSUE_PATTERNS = [/\bERROR\b/, /Exception/, /\tat /];

/** Boot the Folia server with the given plugin jars and analyze the log. */
export async function bootWithPlugins(
  pluginJars: string[],
  pluginNames: string[],
  options: BootOptions = {},
): Promise<BootResult> {
  const serverJar = findServerJar();
  const timeoutMs = (options.timeoutSeconds ?? 420) * 1000;
  const settleMs = (options.settleSeconds ?? 8) * 1000;
  const expect = options.expectMarkers ?? [];
  const scopes = [...(options.pluginScopes ?? []), ...pluginNames, "foliashim"];

  prepareWorkDir(pluginJars);

  const started = Date.now();
  const lines: string[] = [];
  const fatalIssues: string[] = [];
  const noise: string[] = [];
  let reachedDone = false;
  const enabled = new Set<string>();

  const classify = (line: string) => {
    if (ALWAYS_FATAL_PATTERNS.some((p) => p.test(line))) {
      fatalIssues.push(line);
    } else if (GENERIC_ISSUE_PATTERNS.some((p) => p.test(line))) {
      if (scopes.some((s) => line.includes(s))) fatalIssues.push(line);
      else noise.push(line);
    }
  };

  const child = spawn("java", ["-Xms1G", "-Xmx2G", "-jar", serverJar, "--nogui"], {
    cwd: WORK_DIR,
    stdio: ["pipe", "pipe", "pipe"],
  });

  const exitCode: number | null = await new Promise((resolve) => {
    let buffer = "";
    let stopping = false;
    let killTimer: NodeJS.Timeout | null = null;

    const requestStop = () => {
      if (stopping) return;
      stopping = true;
      try {
        child.stdin.write("stop\n");
      } catch {
        child.kill();
      }
      // Hard kill if the server ignores "stop".
      killTimer = setTimeout(() => child.kill(), 90_000);
    };

    const globalTimer = setTimeout(() => {
      fatalIssues.push(`harness: timeout after ${timeoutMs / 1000}s — killing server`);
      requestStop();
      setTimeout(() => child.kill(), 10_000);
    }, timeoutMs);

    const onData = (chunk: Buffer) => {
      buffer += chunk.toString("utf8");
      let nl;
      while ((nl = buffer.indexOf("\n")) >= 0) {
        const line = buffer.slice(0, nl).replace(/\r$/, "");
        buffer = buffer.slice(nl + 1);
        lines.push(line);

        for (const n of pluginNames) {
          if (line.includes(`Enabling ${n}`)) enabled.add(n);
        }
        classify(line);
        if (!reachedDone && /Done \([\d.]+s\)!/.test(line)) {
          reachedDone = true;
          setTimeout(requestStop, settleMs);
        }
      }
    };

    child.stdout.on("data", onData);
    child.stderr.on("data", onData);
    child.on("exit", (code) => {
      clearTimeout(globalTimer);
      if (killTimer) clearTimeout(killTimer);
      resolve(code);
    });
    child.on("error", (err) => {
      fatalIssues.push(`harness: failed to start java: ${err.message}`);
      clearTimeout(globalTimer);
      resolve(null);
    });
  });

  const bootSeconds = (Date.now() - started) / 1000;

  const logFile = path.join(
    "reports",
    `boot-${pluginNames.join("+")}-${new Date().toISOString().replaceAll(":", "-").slice(0, 19)}.log`,
  );
  fs.mkdirSync(path.dirname(logFile), { recursive: true });
  fs.writeFileSync(logFile, lines.join("\n"));

  const joined = lines.join("\n");
  const markersFound = expect.filter((m) => joined.includes(m));
  const markersMissing = expect.filter((m) => !joined.includes(m));

  const missingPlugins = pluginNames.filter((n) => !enabled.has(n));

  return {
    ok: reachedDone && missingPlugins.length === 0 && markersMissing.length === 0 && fatalIssues.length === 0,
    reachedDone,
    enabledPlugins: [...enabled],
    missingPlugins,
    markersFound,
    markersMissing,
    fatalIssues,
    noise,
    exitCode,
    bootSeconds,
    logFile,
  };
}
