import { parseParams } from "./descriptor.js";
import type { EngineIndex, MineResult } from "../types.js";

/**
 * Generates the ShimGenerated class from the mined region catalog: one shim
 * method per void/boolean entity mutator, rerouting to the entity's region
 * scheduler (the exact pattern in Shim, but there are far too many to hand-write).
 * Only methods present in the paper-api we compile against are emitted, so the
 * generated source always compiles.
 */

// name+desc of mutators already hand-written in Shim (skip to avoid clashes).
const HAND_SHIMMED = new Set<string>([
  "teleport(Lorg/bukkit/Location;)Z",
  "teleport(Lorg/bukkit/Location;Lorg/bukkit/event/player/PlayerTeleportEvent$TeleportCause;)Z",
  "teleport(Lorg/bukkit/entity/Entity;)Z",
  "addPotionEffect(Lorg/bukkit/potion/PotionEffect;)Z",
  "addPotionEffect(Lorg/bukkit/potion/PotionEffect;Z)Z",
  "addPotionEffects(Ljava/util/Collection;)Z",
  "removePotionEffect(Lorg/bukkit/potion/PotionEffectType;)V",
  "remove()V",
  "setFireTicks(I)V",
  "setVelocity(Lorg/bukkit/util/Vector;)V",
  "setFallDistance(F)V",
  "setCustomNameVisible(Z)V",
  "setGlowing(Z)V",
  "setGravity(Z)V",
  "setSilent(Z)V",
  "setHealth(D)V",
  "damage(D)V",
  "damage(DLorg/bukkit/entity/Entity;)V",
  "setAI(Z)V",
  "setCollidable(Z)V",
  "setRemoveWhenFarAway(Z)V",
  "setExperience(I)V",
  "pullHookedEntity()Z",
  "customName(Lnet/kyori/adventure/text/Component;)V",
  "setCustomName(Ljava/lang/String;)V",
  "setItemStack(Lorg/bukkit/inventory/ItemStack;)V",
]);

const PRIMITIVES: Record<string, string> = {
  I: "int",
  Z: "boolean",
  D: "double",
  F: "float",
  J: "long",
  B: "byte",
  C: "char",
  S: "short",
  V: "void",
};

function jvmToJava(t: string): string {
  let arr = "";
  while (t.startsWith("[")) {
    arr += "[]";
    t = t.slice(1);
  }
  if (PRIMITIVES[t]) return PRIMITIVES[t] + arr;
  if (t.startsWith("L") && t.endsWith(";")) {
    return t.slice(1, -1).replaceAll("/", ".").replaceAll("$", ".") + arr;
  }
  throw new Error(`unsupported JVM type: ${t}`);
}

export function generateShim(mine: MineResult, paperApi: EngineIndex): { source: string; count: number; skipped: number } {
  // paper-api presence: declaring interface -> set of name+desc it declares.
  const present = new Map<string, Set<string>>();
  for (const c of paperApi.classes) {
    present.set(c.name, new Set(c.methods.map((m) => m.name + m.desc)));
  }

  const seen = new Set<string>();
  const methods: string[] = [];
  let skipped = 0;

  for (const m of mine.api) {
    if (!m.ownerPrefix.startsWith("org/bukkit/entity/")) continue;
    const ret = m.desc.slice(m.desc.indexOf(")") + 1);
    if (ret !== "V" && ret !== "Z") continue; // only void / boolean templates
    const nameDesc = m.name + m.desc;
    if (HAND_SHIMMED.has(nameDesc)) continue;
    if (!seen.has(m.via + "|" + nameDesc)) seen.add(m.via + "|" + nameDesc);
    else continue;
    // Must exist in the API we compile against, on this declaring interface.
    if (!present.get(m.via)?.has(nameDesc)) {
      skipped++;
      continue;
    }

    let paramTypes: string[];
    try {
      paramTypes = parseParams(m.desc).map(jvmToJava);
    } catch {
      skipped++;
      continue;
    }
    const recv = m.via.replaceAll("/", ".");
    const decl = paramTypes.map((t, i) => `${t} a${i}`).join(", ");
    const args = paramTypes.map((_, i) => `a${i}`).join(", ");
    const call = `e.${m.name}(${args})`;
    const params = decl ? `, ${decl}` : "";

    if (ret === "V") {
      methods.push(`    public static void ${m.name}(${recv} e${params}) { Shim.onEntity(e, () -> ${call}); }`);
    } else {
      methods.push(
        `    public static boolean ${m.name}(${recv} e${params}) { if (Shim.ownsEntity(e)) return ${call}; ` +
          `ShimCore.ownScheduler().runAtEntity(e, t -> ${call}); return true; }`,
      );
    }
  }

  const source = `package dev.foliaondemand.shim;

/**
 * AUTO-GENERATED by \`cli mine-folia\` from ${mine.jars[0]?.split(/[\\/]/).pop() ?? "the Folia server jar"}.
 * One shim method per region-locked entity mutator, rerouting the call to the
 * entity's region thread. Do not edit — regenerate with \`npm run cli -- mine-folia\`.
 */
public final class ShimGenerated {
${methods.join("\n")}

    private ShimGenerated() {
    }
}
`;
  return { source, count: methods.length, skipped };
}
